### DISCUSSION TITLE
Global SCSS within module SCSS

### DISCUSSION THREAD

**Discussion by martin-braun** [gatsbyjs/gatsby#29143] [Ideas / Feature Requests] [answered]
EDIT: Intentionally, I was suggesting to enable global selectors in module SCSS, but apparently, this already works:

```scss
.parent1 {
  :global(.child) {
    color: yellow
  }
}
```

So to open this discussion was pointless. Have a good day! :)
