### DISCUSSION TITLE
error "gatsby-source-github-api" threw an error while running the sourceNodes lifecycle:  token is undefined

### DISCUSSION THREAD

**Discussion by sania-dsouza** [gatsbyjs/gatsby#29166] [Help] [answered]
Hello community!

I am new to Gatsby and just tried a GH Actions workflow for my site today. I see this error at the build stage: 

```
error "gatsby-source-github-api" threw an error while running the sourceNodes lifecycle:
token is undefined
```

I am using this to pull all repos on my Github into the site. 

What I have tried so far:
- Checked the Github personal access token 
- the build is working locally

Versions:
"gatsby-source-github-api": "^0.2.1",
"gatsby": "^2.26.1"

This is my node.js.yml GH Actions workflow file:

```
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build


```
Any ideas?
