### DISCUSSION TITLE
Retrieving 2 different collections from config.yml. Gatsby & Netlify CMS

### DISCUSSION THREAD

**Discussion by Afarensis101** [gatsbyjs/gatsby#30269] [Help]
Hi, 

I got a website using Gatsby, and a blog section using Netlify CMS that works just fine. Now, i want to add another section to display products to sell. My teammates asked to have the same netlify admin page for writing both blog posts and product posts. 
From netlify its possible to do this so i wrote another collection in my config.yml file like so : 

config.yml
```
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Teaser", name: "teaser", widget: "text"}

  - name: "market"
    label: "Market"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-post"}
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Reference", name: "reference", widget: "text"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Action -> lien", name: "action", widget: "button"}
      - {label: "Prix", name: "price", widget: "number"}
      - {label: "Overprint", name: "overprint", widget: "text"}
      - {label: "Compteur ", name: "count", widget: "text"}
      - {label: "Image", name: "featuredimage", widget: image}

```

It's working fine on the netlify admin page , users can select blog or market. 

Now i need to add this new collection in the gatsby-node.js file 

```
const _ = require('lodash')
const path = require('path')
const { createFilePath } = require('gatsby-source-filesystem')
const { fmImagesToRelative } = require('gatsby-remark-relative-images')

exports.createPages = ({ actions, graphql }) => {
  const { createPage } = actions

  return graphql(`
    {
      allMarkdownRemark(limit: 1000) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              categories
              tags
              templateKey
            }
          }
        }
      }
    }
  `).then((result) => {
    if (result.errors) {
      result.errors.forEach((e) => console.error(e.toString()))
      return Promise.reject(result.errors)
    }

    const posts = result.data.allMarkdownRemark.edges
    _.each(posts, (post, index) => {
      const articleId = post.node.id
      createPage({
        categories: post.node.frontmatter.categories,
        component: path.resolve(
          `src/templates/${String(post.node.frontmatter.templateKey)}.js`),
        context: {
          id: articleId,
          next: index === 0 ? null : posts[index - 1].node,
          postPath: `/blog${post.node.fields.slug}`,
          previous: index === posts.length - 1 ? null : posts[index + 1].node,
          slug: post.node.fields.slug,
        },
        path: `/blog${post.node.fields.slug}`,
        tags: post.node.frontmatter.tags,
      })
    })
    let categories = []
    posts.forEach((edge) => {
      if(_.get(edge, `node.frontmatter.categories`)) {
        categories = categories.concat(edge.node.frontmatter.categories);
      }
    })
    categories = _.uniq(categories);
    categories.forEach((category) => {
      const categoryPath = `/blog/categories/${_.kebabCase(category)}/`;
      console.log(category)
      createPage({
        path: categoryPath,
        component: path.resolve(`src/templates/categories.js`),
        context: {
          category,
        }
      });
    });

    // Tag pages:
    let tags = []
    // Iterate through each post, putting all found tags into `tags`
    posts.forEach((edge) => {
      if (_.get(edge, `node.frontmatter.tags`)) {
        tags = tags.concat(edge.node.frontmatter.tags)
      }
    })
    // Eliminate duplicate tags
    tags = _.uniq(tags)

    // Make tag pages
    tags.forEach((tag) => {
      const tagPath = `/blog/tags/${_.kebabCase(tag)}/`

      createPage({
        path: tagPath,
        component: path.resolve(`src/templates/tags.js`),
        context: {
          tag,
        },
      })
    })
  })
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions
  fmImagesToRelative(node) // convert image paths for gatsby images

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}
```

I can add something like this : 

```
      createPage({
        path: `/product${post.node.fields.slug}`,
        component: projectPost,
        context: {
          slug: post.node.fields.slug,
          previous: index === posts.length - 1 ? null : posts[index + 1].node,,
          next: index === 0 ? null : posts[index - 1].node,,
        },
      })
```

In the each loop. 

My questions :
How to retrieve only blog datas in my blog post template and only product datas in the product template ?
