### DISCUSSION TITLE
How to enable incremental build in AWS Amplify

### DISCUSSION THREAD

**Discussion by AnilSonix** [gatsbyjs/gatsby#31939] [Help] [answered]
I enabled **.cache and public folder** to be cached in build settings, 
but it seems AWS renames some path on each build (giving me an error that it can't find some file).

Is there any workaround for that?

**Comment by miraclemaker** [comment]
Any update on this?

**Comment by lemoner-rajesh** [comment]
Any update on this ?

**Comment by miraclemaker** [comment]
@lemoner-rajesh I was able to get it working. The problem is that each new build contains the build ID in the path, which breaks the caching since the folder structure contains a hash of the absolute file path. Below is my amplify build.yml which works with the current Amazon Linux 2023 build image. You will need to tweak the paths to suit the path of your frontend code from your repo.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - sudo mkdir -p /build-directory
        - sudo chown amplify /build-directory
        - cp -a ${CODEBUILD_SRC_DIR}/cms-head/frontend/. /build-directory
        - cd /build-directory
        - nvm use 24
        - yarn install --frozen-lockfile
    build:
      commands:
        - npx gatsby build
    postBuild:
      commands:
        - cp -r /build-directory/. ${CODEBUILD_SRC_DIR}/cms-head/frontend
  artifacts:
    baseDirectory: frontend/public
    files:
      - '**/*'
  cache:
    paths:
      - frontend/.cache/**/*
      - frontend/node_modules/**/*
      - frontend/public/**/*
```
