### DISCUSSION TITLE
How to handle broken images in markdown file to query graphql

### DISCUSSION THREAD

**Discussion by Mario8419** [gatsbyjs/gatsby#37527] [Help]
hey there,
i have a markdown file looking like:

```
title: "Summertime 2023"
titleImage: /img/img_8125.jpg
images:
  - img: /img/img_8048.jpg
  - img: /img/img_8066.jpg
  - img: /img/img_8067.jpg
  - img: /img/img_8086.jpg
  - img: /img/img_8125.jpg
  - img: /img/img_8130.jpg
  - img: /img/img_8134.jpg
description: Summer in 2023
```

now let's say one image of those above doesn't exist anymore cause image was deleted through a user directly in the media folder of my cms - so the site is broken and can't be build anymore.

How can I prevent this problem to resolve the graphql query with the remaining images without getting the "Field "img" must not have a selection since type "String" has no subfields." error msg.

thanks in advance
