### ISSUE TITLE
Consider using postcss-import to make CSS variables inlinable from imports

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#10080]
## Summary

Using [postcss-import](https://github.com/postcss/postcss-import), imported CSS rules could be inlined, making it possible to provide static fallbacks for CSS variables, greatly improving cross-browser support.

### Basic example

src/utils/variables.css:

```css
:root {
  --primary-color: red;
}
```

src/pages/index.css:

```css
@import '../utils/variables.css';

body {
  color: var(--primary-color);
    /*
  Outputs:
  color: red;
  color: var(--primary-color);
  */
}
```

### Motivation

In the example above, `color: red;` provides a fallback for older browsers which don't support CSS variables. Other fallbacks or optimizations may also become possible by inlining imported CSS files.
