### ISSUE TITLE
gatsby-plugin-netlify-cms: should image widget fields have subfields?

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#10603]
## Description

I'm getting a weird issue where GraphiQL is showing me that the `thumbnail` field (created by adding an `image` widget field) has subfields, yet I'm getting an error saying the opposite.

![https://d3vv6lp55qjaqc.cloudfront.net/items/1y1s1N3Y3s2a1g470h26/Screen%20Shot%202018-12-21%20at%2018.36.30.png?X-CloudApp-Visitor-Id=43642&v=22a48c56](https://d3vv6lp55qjaqc.cloudfront.net/items/1y1s1N3Y3s2a1g470h26/Screen%20Shot%202018-12-21%20at%2018.36.30.png?X-CloudApp-Visitor-Id=43642&v=22a48c56)

If on the other hand I treat that field as an image, I then get the other error ("must have a selection of subfield") on build…

Is there anything else I need to do to make this work besides adding that image field to my NetlifyCMS config? How does Gatsby deduce the right types for each file from that config file?

### Steps to reproduce

Here's the relevant part of my NetlifyCMS config file:

```
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "blog-post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
```

### Environment

```
System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.1
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.66 => 2.0.66
    gatsby-image: ^2.0.23 => 2.0.23
    gatsby-plugin-netlify: ^2.0.6 => 2.0.6
    gatsby-plugin-netlify-cms: ^3.0.9 => 3.0.9
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4
    gatsby-plugin-sass: ^2.0.7 => 2.0.7
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.7
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-relative-images: ^0.2.0 => 0.2.1
    gatsby-source-filesystem: ^2.0.12 => 2.0.12
    gatsby-source-graphql: ^2.0.7 => 2.0.7
    gatsby-transformer-remark: ^2.1.15 => 2.1.15
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.7
```
