### ISSUE TITLE
pm2 start with gatsby?

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#10992]
I'm trying to get auth0 demo of mine hosted on platform.sh, I keep on running into a 502 Bad gateway error on the callback.

Speaking with the support team at Platform.sh they are saying I need to start nodejs in my `.platform.app.yaml` script.

See documentation here - https://docs.platform.sh/languages/nodejs.html#configuration

What I've got so far.

```
name: app
type: "nodejs:10"

dependencies:
  nodejs:
    pm2: "^2.5.0"
    gatsby-cli: "^1.1.58"

disk: 2048

hooks:
  build: |
    npm install
    gatsby build

web:
  commands:
    start: "PM2_HOME=/app/run pm2 start gatsby -- serve-build --no-daemon"
  locations:
    '/':
      root: 'public'
      index: [ 'index.html' ]
```

I managed to get something together on pm2 from this post here - https://github.com/gatsbyjs/gatsby/issues/604#issuecomment-274650074

I think the magic script is below, but I'm not sure? Anyone have any thoughts.

```
web:
  commands:
    start: "PM2_HOME=/app/run pm2 start gatsby -- serve-build  --no-daemon"
```
