### ISSUE TITLE
[1.0] Question: getting metadata of other pages

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1134]
Let's say I have a **chapter**, like `/getting_started/index.md`:

```yml
---
title: Getting started
---
```

And each chapter is meant to have a **lesson**, like `/getting_started/installation/index.md`:

```yml
---
title: Installation
chapterPath: /getting_started/
---
```

From within my lessons, is it possible to get the chapter's data?

My initial idea is to make lessons React component do a query for `allMarkdownRemark { edges { ... } }` so that it knows ALL pages, then filter those out from within the React component. That seems horribly inefficient.
