### ISSUE TITLE
Update yarn.lock to remove malicious event-stream package

### ISSUE THREAD

**Issue by dakebl** [gatsbyjs/gatsby#13515]
## Description

Whilst trying to set up a new development environment for Gatsby core I noticed that `yarn bootstrap` was failing:
```bash
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
```
This is due to `event-stream-3.3.6.tgz` having been removed from npm, due to a bitcoin exploit: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

### Steps to reproduce

Follow the guide [setting-up-your-local-dev-environment](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/) from scratch. When you come to running `yarn bootstrap`, the installation will error.

### Expected result

Yarn successfully completes `lerna bootstrap`.

### Actual result

The aforementioned error.

### Environment
```yaml
System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.0.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.npm-global/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0.1
    Safari: 12.1
  npmGlobalPackages:
    gatsby: 2.1.4
```
