### ISSUE TITLE
Does `gatsby-plugin-layout` NOT reset scroll position on new routes?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#14634]
So I have an app I'm developing here:

https://github.com/arrowgtp/alma

...that is currently broken in what appears to be the following way:

Without `gatsby-plugin-layout` installed all of the routes reset their scroll position to 0 all the time, which is what I want to happen most (almost all, to be honest) of the time.

But it seems to be the case that after installing `gatsby-plugin-layout` none of the routes reset to 0, but instead it seems that whatever scroll position the current route is on will be maintained in the new route.

For example, if I scroll down the home page maybe a few thousand pixels to the blog entries section, then click on a blog post, I would expect the app to scroll to the top of the blog post, so I can read it, but instead it drops me off somewhere in the middle of the post, forcing me, the user, to scroll up to get to the beginning of the post. This is not good, but it does indeed seem to be the case.

It also seems like the forward and back buttons do not remember the last scroll position of each page, but rather just keep the current scroll position, and push that to the new route, which is super disorienting and awkward for the user.

I want to know if this is indeed an issue with `gatsby-plugin-layout` and if so, then how might I go about controlling scroll position so that I can control when the route resets, persists, or remembers.

Just to re-iterate, without `gatsby-plugin-layout` installed routes work as expected.

Thank you!

CC: @DSchau

**Comment by rchrdnsh** [comment]
Just had a thought @DSchau, could it be possible that the pattern I'm using in CSS to create the apps layout be causing the issue?

Here is the CSS for the `<App>` component:

```css
const App = styled.div`
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  width: 100vw;
  height: 100vh;
  display: grid;
  grid-template-rows: 20vh 70vh 10vh;
  grid-template-columns: repeat(3, 1fr);
  background: white;

  @media (min-width: 50rem) {
    grid-template-rows: 20vh 5vh 55vh 20vh;
    grid-template-columns: 1fr 3fr;
  }

  @media (min-width: 60rem) {
    grid-template-rows: 20vh 5vh 55vh 20vh;
    grid-template-columns: 1fr 4fr;
  }
`
```

...and then each child of the grid decides whether it scrolls or not. Like so:

```css
const Main = styled.main`
  grid-column: 1 / 4;
  grid-row: 1 / 3;
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
  will-change: scroll-position;

  @media (min-width: 50rem) {
    grid-column: 2 / 3;
    grid-row: 1 / 5;
  }
`
```

...where `<Main>` scrolls using overflow-scroll. In the app it's the main section that does not reset scroll position upon each subsequent route, which is the issue I am having. Without `gatsby-plugin-layout` the entire page refreashes (not ideal, but ok) so the main section would refresh it's overflow-y position, but maybe gatsby ins't recognizing the the overflow-scroll position of the `<Main>` component and thus nothing I do in the `gatsby-browser.js` file has any effect on the layout?

I don't want to use position: fixed or any other techniques for layout, as this new approach I'm taking for app layout is, like, totally awesome and amazing and nothing is taken out of the document flow and it's super responsive and wonderful in so many ways.

I dunno, it just hit me that gatsby might be missing the overflow-scroll value of the `<Main>` component nested inside the `<App>` component and not updating it's scroll position on different routes, but I don't know.

Any thoughts you have on this would be lovely :-)
