### ISSUE TITLE
Hosting with automatic build? 

### ISSUE THREAD

**Issue by younggrandpa** [gatsbyjs/gatsby#14740]
## Summary
I'm new to JAMStack implementation and I've reached google search fatigue levels (not to mention information overload). So apologies for the noob question. **Has someone implemented serverless setup where the system periodically builds the gatsby site and purge CDN cache automatically?** I'm looking at either a CRON like system or a trigger via API (e.g. when source database gets X number of records updated, script triggers request for the server to build. I'm leaning towards **_Amazon Web Services_** because of security requirements but happy with other suggestions. 

Thank you in advance.

**Comment by grantglidewell** [comment]
Several hosts implement build hooks if youre looking for something like that. Basically tells the platform that content has changed and triggers a rebuild and push to CDN. Netlify has this, Im sure others are on this train as well.

**Comment by LpmRaven** [comment]
I automatically build my website with AWS code pipeline (I believe the first pipeline is free). I have a branch in my github repo called aws-deployment, whenever new development code is pushed to this branch it deploys to AWS (to S3). I will happily share my build config below.

In the root directory of my codebase, I have a file called `buildspec.yml`(note: indentation needs to be exact in yml files.) Replace all the `waterproofjack.com` bits with the name of your S3 bucket which should match the name of your website. 
```
version: 0.2

phases:
  pre_build:
    commands:
      - npm install --production
      - npm run build
  build:
    commands:
      - aws s3 sync public/static s3://waterproofjack.com/static --metadata-directive REPLACE --cache-control max-age=2419200,public --delete
      - aws s3 sync public s3://waterproofjack.com --metadata-directive REPLACE --cache-control max-age=604800,public --exclude "/static/*" --delete
      - aws s3 cp s3://waterproofjack.com/index.html s3://waterproofjack.com/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Transferred to s3 production environment

```
1. Name your pipeline. NEXT
<img width="799" alt="Screen Shot 2019-06-14 at 1 50 46 pm" src="https://user-images.githubusercontent.com/6523593/59482337-cbb99600-8eab-11e9-8109-42df565cdebf.png">

2. Select Github, connect, select your repo and the branch you wish to deploy from (I don't use master because in my professional career it has been problematic at times). NEXT
<img width="784" alt="Screen Shot 2019-06-14 at 1 51 48 pm" src="https://user-images.githubusercontent.com/6523593/59482433-3965c200-8eac-11e9-9895-b6fed0a73d6c.png">

3. Select create project, this will make a new AWS codebuild. NEXT
<img width="797" alt="Screen Shot 2019-06-14 at 1 57 04 pm" src="https://user-images.githubusercontent.com/6523593/59482505-77fb7c80-8eac-11e9-9b54-76486693f9c1.png">

4. There is some config for the AWS codebuild step but it's all quite straight forward like, 'what kind of build server you want' (mine is Ubuntu). The important bit is to select 'use a buildspec file'. That will get the buildspec file I gave you above from the root directory. NEXT
<img width="819" alt="Screen Shot 2019-06-14 at 1 59 15 pm" src="https://user-images.githubusercontent.com/6523593/59482590-d32d6f00-8eac-11e9-8932-97919ea50639.png">

5. Skip the deploy stage as the build stage has actually deployed it to S3 already. DONE

Hope that helps, let me know if you have any questions about it.
