### ISSUE TITLE
wrapPageElement duplicates/removes CSS classes

### ISSUE THREAD

**Issue by ctcuff** [gatsbyjs/gatsby#15447]
## Description

This issue is similar to [#13235](https://github.com/gatsbyjs/gatsby/issues/13235). [Here is a sample repo](https://github.com/ctcuff/gatsby-error-example) to demonstrate the error. It's not the prettiest code, but I tried to set it up to make it as close as I could to my actual project without making it too bulky.

### Steps to reproduce

1. In the repo I linked above, run `npm install` then `npm run develop`. Visit localhost and everything looks fine.
2. Run `npm run build` then `npm run serve`. When you visit localhost, you'll notice that the style from the sidebar has been stripped and the style from [index page](https://github.com/ctcuff/gatsby-error-example/blob/master/src/pages/index.js) is applied to the [layout component](https://github.com/ctcuff/gatsby-error-example/blob/master/src/components/layout.js)

### Expected result

The styling from `gatsby build` should be the same as `gatsby serve`. This is what everything looks like using `gatsby development` 

This is the landing page, everything is formatted correctly and the HTML is happy:

![Screenshot (61)](https://user-images.githubusercontent.com/7400747/60737855-2d5ca580-9f2a-11e9-8ad8-ce040823580e.png)

Here's what's shown using chrome dev tools (the classes have crazy names since I'm using the `styled-components` plugin):

![correct-formatting](https://user-images.githubusercontent.com/7400747/60737898-4c5b3780-9f2a-11e9-8c72-07e0a32a4046.PNG)

Navigate to any sample post and here's what's shown:

![Screenshot (62)](https://user-images.githubusercontent.com/7400747/60738376-25056a00-9f2c-11e9-8c33-d0ac55467f28.png)

In dev tools:

![correct-sample-post](https://user-images.githubusercontent.com/7400747/60738390-32baef80-9f2c-11e9-83d1-ea4847d2c69c.PNG)

Again, this is all correct. The div with the id `Layout` is what `wrapPageElement` uses ([seen here in the sample repo](https://github.com/ctcuff/gatsby-error-example/blob/master/gatsby-browser.js)).

### Actual result

Run `gatsby build` then `gatsby serve`, head to localhost, and here's what everything looks like:

From the same index page as above (no files were physically changed):

![Screenshot (63)](https://user-images.githubusercontent.com/7400747/60738840-b9240100-9f2d-11e9-8378-d038c14c53be.png)

The index page from dev tools:

![index-error](https://user-images.githubusercontent.com/7400747/60738928-f7212500-9f2d-11e9-87ac-cc5433d1eb9a.PNG)

If you compare it to the screenshot from what should happen, you'll notice that the div that used to have the id `Layout` is now a duplicate of `<div class="pages__Center-ifild7-0 hoBXTv"/>` and the div that wraps the [sidebar component](https://github.com/ctcuff/gatsby-error-example/blob/master/src/components/sidebar.js) (that was previously `<div class="sidebar__Wrapper-eObkgr cZZhxN"/>`) is now a duplicate of the div with the id `Container` (the div that wraps the `Hello world!` text)

Now, navigate to any sample post and here's what you'll see:

![Screenshot (64)](https://user-images.githubusercontent.com/7400747/60739302-677c7600-9f2f-11e9-8e17-cdd90ce64a21.png)

From dev tools:

![post-error](https://user-images.githubusercontent.com/7400747/60739502-305a9480-9f30-11e9-9d9a-b45189f8b794.PNG)

### Temporary fix:

Originally, I thought it might have been an error with the way I was importing my SCSS files and templates (see [this comment](https://github.com/gatsbyjs/gatsby/issues/9911#issuecomment-438912601) from #9911). I even tried removing `.cache` and `node_modules` but was still faced with the same problem.

In order for the components to keep consistent styling throughout `gatsby develop` and `gatsby serve`, I had to wrap the `index` and `sidebar` components with a few divs. Ultimately, this:

``` jsx
export default () => (
  <Center>
    <Container id="Container">Hello world!</Container>
  </Center>
);
```

became this:

```jsx
export default () => (
  <DivWrapper>
    <Center>
      <Container id="Container">Hello world!</Container>
    </Center>
  </DivWrapper>
);
```

where `<DivWrapper/>` is defined in `components/layout.js`:

```jsx
const DivWrapper = ({ children }) => (
  <div>
    <div />
    <div>
      <div>{children}</div>
    </div>
  </div>
);
```

From the sample repo, checkout the [fixes branch](https://github.com/ctcuff/gatsby-error-example/tree/fixes) and you should notice that running `gatsby develop` and `gatsby serve` now show the same layout. 

Side note: in the [fixes branch](https://github.com/ctcuff/gatsby-error-example/tree/fixes), I changed 3 files:

1. [components/layout.js](https://github.com/ctcuff/gatsby-error-example/blob/master/src/components/layout.js) from `master`=> [components/layout.js](https://github.com/ctcuff/gatsby-error-example/blob/fixes/src/components/layout.js) from `fixes`

2. [components/sidebar.js](https://github.com/ctcuff/gatsby-error-example/blob/master/src/components/sidebar.js) from `master` => [components/sidebar.js](https://github.com/ctcuff/gatsby-error-example/blob/fixes/src/components/sidebar.js) from `fixes`

3. [pages/index.js](https://github.com/ctcuff/gatsby-error-example/blob/master/src/pages/index.js) from `maser` => [pages/index.js](https://github.com/ctcuff/gatsby-error-example/blob/fixes/src/pages/index.js) from `fixes`

Side note part 2: I tried wrapping the layout from `layout.js` with the `<DivWrapper/>` and even tried to wrap the `wrapPageElement` with `<DivWrapper/>` but it only seems to work if I wrap individual components and pages

### Environment

``` yaml
System:
    OS: Windows 10
    CPU: (4) x64 AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.4.5
  Browsers:
    Edge: 38.14393.2068.0
  npmPackages:
    gatsby: ^2.11.5 => 2.13.3
    gatsby-mdx: ^0.6.3 => 0.6.3
    gatsby-plugin-layout: ^1.1.0 => 1.1.0
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sass: ^2.1.0 => 2.1.0
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0
    gatsby-source-filesystem: ^2.1.1 => 2.1.2
    gatsby-transformer-remark: ^2.5.0 => 2.6.0
```
