### ISSUE TITLE
Gatsby-Image only sometimes returns selection type "string"

### ISSUE THREAD

**Issue by arnespremberg** [gatsbyjs/gatsby#17939]
Gatsby-Image is working on most of the images coming out of my NetlifyCMS *.md files - but not all of them. Sometimes GraphQL is returning the selection type "string" instead of the Gatsby-Image-objects. I also can't query the image's ID. If I query only the field directly I get a string with the relative path returned.

<img width="1132" alt="Bildschirmfoto 2019-09-27 um 08 03 05" src="https://user-images.githubusercontent.com/52531560/65745861-6b1e3400-e0fd-11e9-8506-9d2446d50872.png">
Error I get when trying to query the image object's ID

<img width="1135" alt="Bildschirmfoto 2019-09-27 um 08 03 20" src="https://user-images.githubusercontent.com/52531560/65746112-2fd03500-e0fe-11e9-8eb0-148e5370048e.png">
"image"-object returning correct items while "portrait"-object queried as string only returning relative path.

in the index.md file that is created by NetlifyCMS the fields syntax is exactly the same.

```
---
templateKey: index-page
galleryImages:
  - first: PHOTOGRAPHERS INSPIRED BY BENE.
    image: /img/wemakestories_bene_parcs_productshooting_slider_quer_01.jpg
    portrait: /img/wemakestories_bene_parcs_productshooting_slider_hoch_01.jpg
    second: BENE
    title: ' '
  - first: GLEICHE CHANCEN. GLEICHE FREIHEIT. GLEICHE RECHTE.
    image: /img/wemakestories_amnesty_oestergleich_kampagne_slider_quer_02.jpg
    portrait: /img/wemakestories_amnesty_oestergleich_kampagne_slider_hoch_02.jpg
    second: AMNESTY INTERNATIONAL
    title: ' '
  - first: ZUKUNFT FÜR DI UND MI.
    image: /img/wemakestories_evn_dachkampagne_superkid_slider_quer_02.jpg
    portrait: /img/wemakestories_evn_dachkampagne_superkid_slider_hoch_02.jpg
    second: EVN
    title: ' '
  - first: SOCIAL TEAM DAY
    image: >-
      /img/wemakestories_caritas_socialteamday_kampagnenbranding_silder_quer_01.jpg
    portrait: >-
      /img/wemakestories_caritas_socialteamday_kampagnenbranding_silder_hoch_01.jpg
    second: CARITAS
    title: '   '
  - first: TAKE AWAY THE LIEBESKUMMER
    image: /img/wemakestories_droetker_takeaway_tvspot_slider_quer_01.jpg
    portrait: /img/wemakestories_droetker_takeaway_tvspot_slider_quer_01.jpg
    second: DR. OETKER
    title: '  '
  - first: DIE ERBSENREISE
    image: /img/wemakestories_iglo_erbsenreise_kampagne_slider_quer_01.jpg
    portrait: /img/wemakestories_iglo_erbsenreise_kampagne_slider_hoch_01.jpg
    second: IGLO ÖSTERREICH
    title: '  '
  - first: EIN THINKTANK DER VIELEN.
    image: /img/wemakestories_momentum_branding_slider_quer_02.jpg
    portrait: /img/wemakestories_momentum_branding_slider_hoch_02.jpg
    second: MOMENTUM INSTITUT.
    title: ' '
  - first: AMNESTY INTERNATIONAL
    image: /img/wemake_amnesty_anzeigebild_quer.jpg
    portrait: /img/190318_amnesty_instagram_9zu16_2.jpg
    second: GLEICHE CHANCEN. GLEICHE FREIHEIT. GLEICHE RECHTE.
    title: ' '
---
```

The config.yml of NetlifyCMS also seems correct to me:

```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Start"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Slider", name: "galleryImages", widget: "list", fields: [
            {label: "Querformat", name: "image", widget: "image"},
            {label: "Hochformat", name: "portrait", widget: "image", required: "false"},
            {label: "Title", name: "title", widget: "string", required: "false"},
            {label: "1. Zeile", name: "first", widget: "string", required: "false"},
            {label: "2. Zeile", name: "second", widget: "string", required: "false"},
          ]}
```

I have seen similar issues with the same error message but on ALL the images. In this case, only SOME of the images get this error. For some of those, the order of the plugin list in the `gatsby-config.js` seemed to fix it. I tried several different orders, but none of them worked for me. I will paste you my config file here anyways

```
var proxy = require('http-proxy-middleware')

module.exports = {
  siteMetadata: {
    title: 'WMS',
    description:
    'We Make Stories ist Österreichs führende Agentur an der Schnittstelle zwischen klassischer und digitaler Kommunikation.',
  },
  plugins: [
    {
      // keep as first gatsby-source-filesystem plugin for gatsby image support
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/static/img`,
        name: 'uploads',
      },
    },
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-relative-images',
            options: {
              name: 'uploads',
            },
          },
          {
            resolve: 'gatsby-remark-images',
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 4096,
            },
          },
          {
            resolve: 'gatsby-remark-copy-linked-files',
            options: {
              destinationDir: 'static',
            },
          },
        ],
      },
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/assets/img`,
        name: 'images',
      },
    },
    // 'gatsby-plugin-transition-link',
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
    // {
    //   resolve: 'gatsby-plugin-purgecss', // purges all unused/unreferenced css rules
    //   options: {
    //     develop: true, // Activates purging in npm run develop
    //   },
    // }, // must be after other CSS plugins
    'gatsby-plugin-netlify', // make sure to keep it last in the array
  ],
  // for avoiding CORS while developing Netlify Functions locally
  // read more: https://www.gatsbyjs.org/docs/api-proxy/#advanced-proxying
  developMiddleware: app => {
    app.use(
      '/.netlify/functions/',
      proxy({
        target: 'http://localhost:9000',
        pathRewrite: {
          '/.netlify/functions/': '',
        },
      })
    )
  },
}
```

### Expected result

Getting the same expected Gatsby-Image-Object as with the other images on my site. 

### Actual result

Returns string, not Object

**Thank all of you so much for your great work! I love Gatsby and I hope we will solve this issue together. Looking forward to your answers!**
