### ISSUE TITLE
Build .cache and AWS Amplify / Codebuild

### ISSUE THREAD

**Issue by sirichards** [gatsbyjs/gatsby#17990]
Hi,

I am using AWS Amplify to build my Gatsby app, to speed the build time up I have included the .cache folder in the yaml build spec. The problem with this is AWS creates a new instance for each build, the build id is contained in the folder structure, therefore the absolute paths Gatsby stores in the .cache files are invalid for future builds.

e.g. /codebuild/output/src245632857/src/my-website/.cache/

The next build would have a completely different id, changing the path, this will eventually cause an error in the build.

[WARNING]: error Input file is missing
Failed to process image /codebuild/output/src609089159/...

Is there a way around this, could these paths be made relative?

Thanks

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd suggest contacting the AWS support about this issue as it doesn't seem related to Gatsby. You can't make these paths relative.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by kyleboss** [comment]
@sirichards , I think I have found a work-around. Gatsby probably cannot fix this because these paths need to be absolute. However, what we can do is use create our own build-directory each and every time. 

*buildspec.yml*
```
version: 0.2

phases:
  pre_build:
    commands:
      - mkdir -p /build-directory
      - cp -a ${CODEBUILD_SRC_DIR}/. /build-directory
      - cd /build-directory
      - yarn
  build:
    commands:
      - cd /build-directory
      - gatsby build
  post_build:
    commands:
      - cd /build-directory
      - cp -a /build-directory/. ${CODEBUILD_SRC_DIR}
cache:
  paths:
    - 'node_modules/**/*'
    - 'public/**/*'
    - '.cache/**/*'
```

Gatsby assumes that the absolute path to `.cache` is consistent between builds. This is not very compatible with CodeBuild since the build directory changes for each build. Because of this, Gatsby isn't able to locate the cached files and throws an error.

For this reason, creating a consistent path and bringing the artifacts there will solve the issue. When the build is done, be sure to bring the new artifacts to the `CODEBUILD_SRC_DIR` so that they can be cached for next time!

**Comment by sirichards** [comment]
@kyleboss that seems to work! Good work-around for now, thanks.

**Comment by LpmRaven** [comment]
This is the same issue I have, although creating a build folder might be a problem due to the size of my site. I have around 300k pages + images which equates to about 50GB of files. Is the CODEBUILD_SRC_DIR the same directory you are in ag the start of each phase? Just trying to think of a workaround for the `cp -a /build-directory/. ${CODEBUILD_SRC_DIR}` step.

**Comment by andrea689** [comment]
@LpmRaven instead of copying the folder, you can rename it.

```yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd ../../..
        - mv $(cut -d'/' -f4 <<<"$CODEBUILD_SRC_DIR") build-dir
        - cd build-dir/src/<INSERT_AMPLIFY_PROJECT_NAME>
        - npm ci
    build:
      commands:
        - npm run build
    postBuild:
      commands:
        - cd ../../..
        - mv build-dir $(cut -d'/' -f4 <<<"$CODEBUILD_SRC_DIR")
        - cd $CODEBUILD_SRC_DIR
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .cache/**/*
      - public/**/*
```

**Comment by badaczewski** [comment]
I found one issue with this solution I had to work around that might help others.

CodeBuild has an annoying script that will run after each command to try to set your shell back to the proper working directory. You can read about it here, https://www.gadjev.com/2021/10/15/aws-codebuild-fails-when-changing-to-a-folder-directory-with-a-space/

I was getting an error after a Gatsby build and/or Gatsby deploy to S3. This is this scripts keeps reseting a text file called "dir.txt" in an outdated manner causing my commands to execute from the wrong location.

Since we are only concerned about making use of the .cache for the build process I only needed to temporarily trick CodeBuild into building under the path I wanted it to, after that it can continue as normal. This is what my code looks like (with sanitization).

```yaml
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yarn
      - yarn global add gatsby-cli
  pre_build:
    commands:
      - src=$(cd ../../../../.. && pwd)
      - yarn --ignore-optional
  build:
    commands:
      - mv $src /codebuild/output/build && GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages && mv /codebuild/output/build $src
  post_build:
    commands:
      - npm run-script deploy && aws cloudfront create-invalidation --distribution-id XXXXXXXXXX --paths '/*'
artifacts:
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
    - 'node_modules/**/*'
    - 'public/**/*'
    - '.cache/**/*'
```

It's not beautiful, but I like how it's error free, does what I need and then sets CodeBuild back to the way it was in one line.
