### ISSUE TITLE
Cannot extend inferred GraphQL type due to "multiple types" error

### ISSUE THREAD

**Issue by ndresx** [gatsbyjs/gatsby#18080]
## Summary

Hi, I'm trying to extend a from Gatsby inferred GraphQL type called `MdxExportsData` as you can see below by using the `createSchemaCustomization` API, but somehow, all the attempts I have tried so far failed because of the following error message:

```
Error: Schema must contain uniquely named types but contains multiple types named "MdxExportsData".

  - Array.reduce
  
  - SchemaComposer.js:130 SchemaComposer.buildSchema
    [graphql-compose]/lib/SchemaComposer.js:130:12
  
  - schema.js:661 buildSchema
    [gatsby]/src/schema/schema.js:661:45
  
  - schema.js:166 addCustomResolveFunctions
    [gatsby]/src/schema/schema.js:166:9
```

I have also tried to extend it via `extend` and other variations, but that doesn't seem to be supported by Gatsby.

This is how the existing type looks like if it would get written into a schema file _(I've used `gatsby-plugin-schema-snapshot` to do that)_. 

`schema.gql`
```gql
type MdxExportsData {
  name: String
}
```
The goal would be to extend this type with an optional `rank` field.

`gatsby-node.js`
```ts
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    type MdxExportsData @infer {
      rank: Int
    }
  `);
};
```

Any help would be appreciated at this point, thank you!

### Environment (if relevant)

```
  npmPackages:
    gatsby: 2.15.28 => 2.15.28
    gatsby-image: ^2.0.37 => 2.2.23
    gatsby-plugin-catch-links: ^2.0.10 => 2.1.12
    gatsby-plugin-google-tagmanager: ^2.0.13 => 2.1.12
    gatsby-plugin-mdx: 1.0.40 => 1.0.40
    gatsby-plugin-react-helmet: ^3.0.6 => 3.1.10
    gatsby-plugin-react-svg: ^2.0.0-beta1 => 2.1.2
    gatsby-plugin-schema-snapshot: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.0.0 => 2.2.27
    gatsby-plugin-styled-components: ^3.0.5 => 3.1.8
    gatsby-plugin-typescript: ^2.0.0 => 2.1.11
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-remark-autolink-headers: ^2.0.0 => 2.1.13
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.23
    gatsby-remark-embed-youtube: ^0.0.7 => 0.0.7
    gatsby-remark-images: 3.1.2 => 3.1.2
    gatsby-remark-lazy-load: ^1.0.1 => 1.0.2
    gatsby-remark-prismjs: ^3.0.0 => 3.3.16
    gatsby-source-filesystem: 2.0.39 => 2.0.39
    gatsby-transformer-json: ^2.1.11 => 2.2.11
    gatsby-transformer-sharp: ^2.1.1 => 2.2.19
```
