### ISSUE TITLE
[mdx + schema-snapshot] "Source and transform nodes" step gets skipped?

### ISSUE THREAD

**Issue by ndresx** [gatsbyjs/gatsby#18095]
## Description

Hey! I'm using the `gatsby-plugin-mdx` plugin and wanted to lock down my GraphQL typings/schema with `gatsby-plugin-schema-snapshot` to see how it would behave, but after running it twice, it doesn't seem to be picking up the file contents any longer and just breaks.

### Steps to reproduce

1. **Run `gatsby develop` for the first time (lock-file is not available yet).**
The lock-file gets generated and all the fields (including the `Mdx.body` are populated within the queries). Everything looks fine, plus, the generated typing declared the body as a `non-nullable` value ( `String!`), which is also correct.
2. **Re-run `gatsby develop` with the lock-file in place.**
It almost seems to be skipping the `source and transform nodes` step (compared to the first run where it takes minutes) and breaks in the end because of the `Mdx.body` values, which are `null` now altogether. The `rawBody`, however, is still populated.

### Expected result

I guess it should just pick up all the content again and process ``source and transform nodes` like it was doing it correctly in the first run.

### Actual result

The `mdx.body` values are `null`. The queries now break because of this, even though the content hasn't been changed.

### Environment

```
  npmPackages:
    gatsby: 2.15.28 => 2.15.28
    gatsby-image: ^2.0.37 => 2.2.23
    gatsby-plugin-catch-links: ^2.0.10 => 2.1.12
    gatsby-plugin-google-tagmanager: ^2.0.13 => 2.1.12
    gatsby-plugin-mdx: 1.0.40 => 1.0.40
    gatsby-plugin-react-helmet: ^3.0.6 => 3.1.10
    gatsby-plugin-react-svg: ^2.0.0-beta1 => 2.1.2
    gatsby-plugin-schema-snapshot: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.0.0 => 2.2.27
    gatsby-plugin-styled-components: ^3.0.5 => 3.1.8
    gatsby-plugin-typescript: ^2.0.0 => 2.1.11
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-remark-autolink-headers: ^2.0.0 => 2.1.13
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.23
    gatsby-remark-embed-youtube: ^0.0.7 => 0.0.7
    gatsby-remark-images: 3.1.2 => 3.1.2
    gatsby-remark-lazy-load: ^1.0.1 => 1.0.2
    gatsby-remark-prismjs: ^3.0.0 => 3.3.16
    gatsby-source-filesystem: 2.0.39 => 2.0.39
    gatsby-transformer-json: ^2.1.11 => 2.2.11
    gatsby-transformer-sharp: ^2.1.1 => 2.2.19
```
