### ISSUE TITLE
New Translation Request - Simplified Chinese

### ISSUE THREAD

**Issue by xiyizhou** [gatsbyjs/gatsby#18486]
```yaml
name: Simplified Chinese
code: zh-Hans
maintainers:
  - xiyizhou
  - nelsonkuang
  - QC-L
  - zhouyuexie
```
