### ISSUE TITLE
New Translation Request - Traditional Chinese

### ISSUE THREAD

**Issue by dsewnr** [gatsbyjs/gatsby#19284]
```yaml
name: Traditional Chinese
code: zh-Hant
maintainers:
- dsewnr
- hiimdoublej
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
