### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by jaisadana19** [gatsbyjs/gatsby#19403]
```yaml
name: English
code: en
maintainers:
  - tesseralis
  - marcysutton
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
