### ISSUE TITLE
Images as properties inside objects in frontmatter array

### ISSUE THREAD

**Issue by gmossong** [gatsbyjs/gatsby#20004]
I am unsure if this is a bug, an error on my part or a feature that Gatsby doesn't yet handle. In my frontmatter I have an array `steps` with objects, each object has properties (name, text, image and url):

```
Title: How to paint a wall
cover: "./how-to-pain-a-wall.jpg"
steps:
  - name: Paint the wall with undercoat
    text: Use a large bush to apply undercoat
    image: "./large-brush.jpg"
    url: "#paint-wall"
  - name: Apply topcoat
    text: Use a fine bush to apply topcoat
    image: "./fine-brush.jpg"
    url: "#apply-top-coat"
...
```
When using graphql I am not seeing all the options for `image` that I do with `cover`. I'd like to get the publicURL for the `image` in each `step`.

![steps](https://user-images.githubusercontent.com/18605121/70395420-54804b80-1a63-11ea-8799-df963db77ec1.png)
