### ISSUE TITLE
Norwegian, bokmål -nb

### ISSUE THREAD

**Issue by webmaeistro** [gatsbyjs/gatsby#20136]
```yaml
name: Norwegian bokmål
code: nb
maintainers:
  - webmaeistro
  - leokarts
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
