### ISSUE TITLE
How to merge media queries with same conditions?

### ISSUE THREAD

**Issue by in-in** [gatsbyjs/gatsby#20133]
## Summary
I use `gatsby-plugin-sass` and nested _media queries_ for each CSS class.

```css
.header {
  background-color: rebeccapurple;

  @media (min-width: 480px) {
    background-color: seagreen;
  }

  @media (min-width: 640px) {
    background-color: purple;
  }

  @media (min-width: 960px) {
    background-color: slateblue;
  }
}
```

After the `npm run build` command, my production CSS file is bloated because there are a lot of extra _media queries_. In an ideal world, I want all the rules relating to the same _media queries_ to be within that query and not duplicated.

I tried to use [postcss-combine-media-query](https://github.com/SassNinja/postcss-combine-media-query) plugin that was supposed to help me to merge all the _media queries_, but that didn't happen. I do not know exactly why, it seems that this plugin does not have access to the final CSS file.

## Relevant information

Demo project: https://github.com/in-in/gatsby-starter-default

### Environment (if relevant)

<details>
 <summary>Environment</summary>
  System:<br>
  OS: Linux 4.15 Linux Mint 19.2 (Tina)<br>
  CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz<br>
  Shell: 5.4.2 - /usr/bin/zsh<br>
Binaries:<br>
  Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node<br>
  npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm<br>
Languages:<br>
  Python: 2.7.15+ - /usr/bin/python<br>
Browsers:<br>
  Firefox: 72.0b6<br>
npmPackages:<br>
  gatsby: ^2.18.8 => 2.18.11 <br>
  gatsby-image: ^2.2.34 => 2.2.36 <br>
  gatsby-plugin-manifest: ^2.2.31 => 2.2.33 <br>
  gatsby-plugin-offline: ^3.0.27 => 3.0.29 <br>
  gatsby-plugin-react-helmet: ^3.1.16 => 3.1.18 <br>
  gatsby-plugin-sass: ^2.1.26 => 2.1.26 <br>
  gatsby-plugin-sharp: ^2.3.5 => 2.3.7 <br>
  gatsby-source-filesystem: ^2.1.40 => 2.1.42 <br>
  gatsby-transformer-sharp: ^2.3.7 => 2.3.9 <br>
</details>

### File contents (if changed)

`gatsby-config.js`: 
```js
...
{
      resolve: 'gatsby-plugin-sass',
      options: {
        implementation: require('sass'),
        includePaths: ['./src'],
        cssLoaderOptions: {
          localIdentName: '[local]--[hash:base64:5]',
          camelCase: false,
        },
        postCssPlugins: [
          require('postcss-logical'),
          require('postcss-combine-media-query'),
        ]
      },
    },
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`:
```js
import("./src/styles/index.scss")
```
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to the author of this PostCSS plugin as it might be the case that your code shown above is not supported - since it doesn't show nested queries in its README: https://github.com/SassNinja/postcss-combine-media-query

Feel free to comment here if you or you both can verify that it should work nevertheless and you're sure that it's a bug in Gatsby.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by in-in** [comment]
It's obvious that the plugin doesn't have nested queries problems because it works with AST.

Moreover, I double-checked my code by rewriting it into a flat structure.
```css
.header {
  background-color: rebeccapurple;
}

@media (min-width: 480px) {
  .header {
    background-color: seagreen;
  }
}

@media (min-width: 640px) {
  .header {
    background-color: purple;
  }
}

@media (min-width: 960px) {
  .header {
    background-color: slateblue;
  }
}
```
The result is the same - an bloated final CSS file.

And the main problem is not in the plugin but in the fact that Gatsby doesn't have any opportunity to remove unnecessary CSS code.


Feel free to keep this issue closed :+1: 
Because it's the easiest way to solve this problem.
