### ISSUE TITLE
New Translation Request - Finnish

### ISSUE THREAD

**Issue by endormi** [gatsbyjs/gatsby#20327]
```yaml
name: Finnish
code: fi
maintainers:
  - endormi
  - rennehir
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source: I maintain a few open source projects and contribute to many.
- your level of experience in the target language and localization: It's my native language.
- how much time you can commit to being a maintainer: Once a week.
