### ISSUE TITLE
Robots.txt is getting generated from somewhere

### ISSUE THREAD

**Issue by DavidBarnes761** [gatsbyjs/gatsby#20387]
## Description
Hello. I'm loving Gatsby! Just started working on my second Gatsby project and realized that both of my sites are creating a robots.txt file that is disallowing the sites to be crawled. This is a huge issue for me and my company and I need to figure out how to fix it asap. Please, any advice would be appreciated.

Both sites show a generated robots.txt file with:
```
User-agent: *
Disallow: /
```

https://www.floorforce.com/robots.txt
http://broadlume.surge.sh/robots.txt

Demo link:
https://github.com/DavidBarnes761/robots.txt-demo

### Steps to reproduce
I ran an SEO check on the sites' and that's how I discovered my sites are not being crawled by Google.

Navigate to /robots.txt

### Expected result

I've added the 'gatsby-plugin-robots-txt' and have it added to my gatsby-config.js

```
{
  resolve: 'gatsby-plugin-robots-txt',
  options: {
    host: 'https://www.broadlume.com',
    sitemap: 'https://www.broadlume.com/sitemap.xml',
    policy: [{ userAgent: '*', allow: '/' }],
  },
 },
```

The result within the robots.txt file should be:

```
User-agent: *
Allow: /
```

### Actual result

```
User-agent: *
Disallow: /
```

### Environment

```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.10 => 2.18.14
    gatsby-awesome-pagination: ^0.3.3 => 0.3.5
    gatsby-background-image: ^0.9.7 => 0.9.12
    gatsby-image: ^2.2.33 => 2.2.37
    gatsby-plugin-google-marketing-platform: ^0.1.17 => 0.1.18
    gatsby-plugin-google-tagmanager: ^2.1.20 => 2.1.20
    gatsby-plugin-htaccess: ^1.3.2 => 1.3.2
    gatsby-plugin-lodash: ^3.1.7 => 3.1.18
    gatsby-plugin-manifest: ^2.2.29 => 2.2.33
    gatsby-plugin-netlify: ^2.1.12 => 2.1.30
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.26 => 2.1.26
    gatsby-plugin-sharp: ^2.3.7 => 2.3.9
    gatsby-plugin-sitemap: ^2.2.24 => 2.2.24
    gatsby-plugin-typescript: ^2.1.22 => 2.1.23
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-images: ^3.1.37 => 3.1.38
    gatsby-source-filesystem: ^2.1.42 => 2.1.42
    gatsby-source-wordpress: ^3.1.53 => 3.1.53
    gatsby-transformer-remark: ^2.6.42 => 2.6.44
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.8.22
```

**Comment by daugsbi** [comment]
Is your environment variable set to production? It is taken from process.env.NODE_ENV.

I've checked your repository and it works. So what I've done is:

```
yarn install
yarn build
```

And then I checked the file public/robots.txt.
```
User-agent: *
Allow: /
Sitemap: https://www.broadlume.com/sitemap.xml
Host: https://www.broadlume.com
```

Maybe you need to set the variable in your Netlify build environment. 
https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-environment

**Comment by DavidBarnes761** [comment]
Thank you for the response. We're not using Netlify for deployment so maybe I can just remove Netlify from the project.

I suppose what I need to do is remove the netlify dependency in my package.json and remove the netlify.toml file?

Maybe once that's completed and I run `gatsby build` it will fix the issue when it's deployed.

**Comment by daugsbi** [comment]
If you don't use netlify you can try to set it before the build.
`NODE_ENV=production gatsby build`

The behavior is strange, because it should be set automatically for the build command. Do you have an .env file in your project

**Comment by DavidBarnes761** [comment]
I do not have an .env file

**Comment by DavidBarnes761** [comment]
I removed netlify as a dependency, reran npm install and gatsby build, and it's still showing that robot.txt file

**Comment by DavidBarnes761** [comment]
http://ff-website.surge.sh/robots.txt

**Comment by daugsbi** [comment]
Is it only on surge.sh? I found this one:
https://stackoverflow.com/questions/54262130/surge-sh-does-not-allow-to-modify-robots-txt

**Comment by DavidBarnes761** [comment]
No, it's found on the live site

https://www.floorforce.com/robots.txt

**Comment by daugsbi** [comment]
How does the file public/robots.txt looks like before you deploy it?

**Comment by DavidBarnes761** [comment]
Looks like this:

User-agent: *
Allow: /
Sitemap: https://www.floorforce.com/sitemap.xml
Host: https://www.floorforce.com

![Screen Shot 2020-01-03 at 11 05 14 AM](https://user-images.githubusercontent.com/4673033/71734027-f30c8c00-2e18-11ea-8d0a-2638a4be1ac7.png)

**Comment by daugsbi** [comment]
That looks correct :+1: 
So there must be either a server directive or config that prevents delivering the robots.txt file or the file is not deployed correctly (i. e. not overwriting existing files while syncing)

**Comment by DavidBarnes761** [comment]
I created a temp account on our Godaddy server and manually deployed the site there and it looks good

http://robots.floorforce.com/robots.txt

**Comment by DavidBarnes761** [comment]
I did not set up the deployment process for this site. Should the public/ folder be included in the gitignore file? Shouldn't that folder be part of the repo?

I've attached the CircleCI config.yml.

It looks like it's utilizing www-floorforce.surge.sh for production...that can't be right

```
---
version: 2.0
jobs:
  build:
    working_directory: ~/ff-website
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM packages
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Check the codebase for linting errors
          command: yarn run lint:check
      - run:
          name: Check the codebase for formatting errors
          command: yarn run format:check
      - run:
          name: Build Gatsby site
          command: yarn build
      - deploy:
          name: Deploy if on master branch
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              yarn run surge ./public www-floorforce.surge.sh
            else
              echo "Not on master branch, skipping deploy step..."
            fi

```
