### ISSUE TITLE
Marathi Translation 

### ISSUE THREAD

**Issue by spielers** [gatsbyjs/gatsby#21142]
```yaml
name: Marathi
code: mr
maintainers:
  - spielers
  - Gamitics
  - visshaljagtap 
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
