### ISSUE TITLE
Marathi language translation

### ISSUE THREAD

**Issue by spielers** [gatsbyjs/gatsby#21143]
```yaml
name: Marathi
code: mr-In
maintainers:
  - spielers
  - Gamitics
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
