### ISSUE TITLE
How can I resolve url('//xxx.cdn.com/xxx') in stylesheet?

### ISSUE THREAD

**Issue by harbin1053020115** [gatsbyjs/gatsby#22082]
## Summary

There is a url('//at.cdn.com/xxx') in my css file, but when the stylesheet linked with blob-based(blob:http://), browser cannot load url('//at.cdn.com/xxx')...

## Relevant information

This is my css file: 

```css
@font-face {
  font-family: NextIcon;
  src: url("//at.alicdn.com/t/font_515771_7u6frotlpa6.eot");
  src: url("//at.alicdn.com/t/font_515771_7u6frotlpa6.eot?#iefix") format("embedded-opentype"), url("//at.alicdn.com/t/font_515771_7u6frotlpa6.woff2") format("woff2"), url("//at.alicdn.com/t/font_515771_7u6frotlpa6.woff") format("woff"), url("//at.alicdn.com/t/font_515771_7u6frotlpa6.ttf") format("truetype"), url("//at.alicdn.com/t/font_515771_7u6frotlpa6.svg#NextIcon") format("svg"); 
}
```

But the stylesheet is linked by:

```html
<link type="text/css" rel="stylesheet" href="blob:http://xxx" />
```

My question is:

The webfont link url("//at.alicdn.com/t/font_515771_7u6frotlpa6.eot") will not loaded by browser

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A
