### ISSUE TITLE
reduxcache* folders are not deleted starting at gatsby 2.19.22 in Docker containers

### ISSUE THREAD

**Issue by asgarli** [gatsbyjs/gatsby#22562]
## Description

I have a Docker setup for Gatsby with the following configuration:
```yml
# docker-compose.yml
version: '3'
services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    volumes:
      - /app/.cache
      - /app/node_modules
      - /app/public
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1
```
```
# Dockerfile
FROM node:12
EXPOSE 8000 9929 9230

RUN npm i -g gatsby-cli
RUN gatsby telemetry --disable

WORKDIR /app
COPY ./package.json .
RUN npm i

# Run with `gatsby develop -H 0.0.0.0`
```
```
# .dockerignore
./.cache
./node_modules
./public
```

When I run `gatsby develop`, I get the following error:
```
warn Error persisting state: ENOENT: no such file or directory, rename 'reduxcacheF9pfSE' -> '/app/.cache/redux'
warn Error persisting state: ENOENT: no such file or directory, rename 'reduxcache7D8wgJ' -> '/app/.cache/redux'
warn Error persisting state: ENOENT: no such file or directory, rename 'reduxcacheCPgs5R' -> '/app/.cache/redux'
```

This happens with version 2.19.22, and not with version 2.19.21. I was getting another error earlier, saying something along the lines of cannot move files between incompatible systems. My Docker is on Windows, using Linux VM. I believe the error comes from trying to use system calls for moving files instead of npm package, but I might be wrong, since I don't know JS well enough to debug this.

### Steps to reproduce

Described above

### Expected result

Described above

### Actual result

Described above

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: 2.19.22 => 2.19.22
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-plugin-google-analytics: ^2.2.1 => 2.2.1
    gatsby-plugin-manifest: ^2.3.2 => 2.3.2
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.1.1 => 3.1.1
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-transformer-sharp: ^2.4.2 => 2.4.2
  npmGlobalPackages:
    gatsby-cli: 2.11.1
```
