### ISSUE TITLE
New Translation Request - Catalan

### ISSUE THREAD

**Issue by eduayme** [gatsbyjs/gatsby#22776]
```yaml
name: Catalan
code: ca
maintainers:
  - eduayme
  - siddux
```

**Maintainers**

- *Experience level in open source:* I have experience managing my own open source project and contributing to other small open source projects.

- *Experience in the target language and localization:* I am a Catalan and Spanish native speaker currently living in Madrid, Spain.

- *How much time you can commit to being a maintainer:* As a maintainer I can commit for 4h or 5h per week depending on the dates.
