### ISSUE TITLE
Graphql field missing

### ISSUE THREAD

**Issue by emmadigital** [gatsbyjs/gatsby#23909]
## Summary
I am using gatsby netlify cms starter theme: https://github.com/netlify-templates/gatsby-starter-netlify-cms I have added category field for my blog posts, the mark down file has this entry but it's missing in Graphql explorer https://prnt.sc/sd81la any suggestions

**md file**
```
tags:
  - year in review
category: 
  - personal
  - software-development
```

## Relevant information
` 181:9  error  Cannot query field "category" on type "MarkdownRemarkFrontmatter"  graphql/template-strings`

**Graphql Query**
```
  query BlogPostByID($id: String!) {
    markdownRemark(id: { eq: $id }) {
      id
      html
      frontmatter {
        title
        description
        tags
        category
       }
    }
  }
```
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
Hi @emmadigital!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by emmadigital** [comment]
> Hi @emmadigital!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

Hi @DSchau, here is my repo: https://github.com/emmadigital/ardalis-newsite

**Comment by emmadigital** [comment]
Hi @DSchau any suggestions why the category field not showing up in Graphql.

**Comment by wardpeet** [comment]
I saw the following inside the cli:
```
success source and transform nodes - 1.619s
warn There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
MarkdownRemark.frontmatter.category:
 - type: array
   value: [ ..., 'productivity', ... ]
 - type: string
   value: 'personal'
```

This means your category doesn't have a consistent type. You should move everything to an array instead so `"personal"` becomes `["personal"]`

**Comment by wardpeet** [comment]
Thank you for opening this, @emmadigital

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by emmadigital** [comment]
@wardpeet thank you for your response, can you please explain where do i need to make these changes insise confi.yml file?

```
      - label: Tags
        name: tags
        widget: list
      - label: Category
        name: category
        widget: select
        multiple: true        
        options:
          - label: Iraq
            value: iraq
          - label: Personal
            value: personal
          - label: Productivity
            value: productivity
          - label: Security
            value: security
          - label: Software Development
            value: software-development
          - label: Uncategorized
            value: uncategorized
```
