### ISSUE TITLE
GraphQL - Pulling back related data between markdown files

### ISSUE THREAD

**Issue by jf-home** [gatsbyjs/gatsby#25512]
Hi, 

I have a content setup (markdown files) containing several products and within each a category array for the classification that each product falls into, i.e.: 

ProductA.md

```markdown
template: product
title: ProductA
description: Some text in here 
category: [car, mechanical, electrical]`
```

ProductB

```markdown
template: product
title: ProductB
description: Some text in here 
category: [motorbike, mechanical, electrical]
```

ProductC

```markdown
template: product
title: ProductC
description: Some text in here 
category: [pushbike, mechanical]
```

My config.yml is as follows:

```yaml
  - name: "products"
    label: "Products"
    folder: "src/content/product"
    create: true
    slug: "{{slug}}"
    widget: "object"
    editor:
     preview: false
    fields:
      - { label: "Template", name: "template", widget: "select", options: ["product"] }
      - { label: Title, name: title, widget: string }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: Category
        name: category
        widget: "relation"
        collection: "categories"
        multiple: true
        searchFields: ['name']
        valueField: "{{slug}}"
        displayFields: ["name"]
  - name: "categories"
    label: "Categories"
    folder: "src/content/categories"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "ID", name: "category_id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
```

I'd like to be able to pull a list of products back, by category, but I haven't found a way of doing this.  

I have tried mapping in gatsby-config.js: 

```js
  mapping: {
    'MarkdownRemark.frontmatter.category': `MarkdownRemark.frontmatter.category_id`
  },
```

...but to no avail!  

I have also tried a few of te examples using createSchemaCustomization in my gatsby-node.js, but I'm stuggling to find an example that matches my requirement and am therefore at a bit of a loss!   

I'd be incredibly grateful if someone can give me a steer on this!  

Thanks in advance.
