### ISSUE TITLE
Content Manager doesn't display entries organized in subfolders by custom slug

### ISSUE THREAD

**Issue by Kaltoft** [gatsbyjs/gatsby#25725]
## Description

When using a collection with custom `slug` that organizes the content by folder the CMS Admin panel won't display these entries. They are successfully created in the admin section and appears in the list of entries as expected right after, however when the page is refreshed they don't show up.

They are created as expected in a folder structure looking like this:

```bash
──src
  | ├── content
  | │   ├── news
  | │   │   ├── 2020
  | │   │   │   ├── 05
  | │   │   │   ├── 06
  | │   │   │   ├── 07
  | │   │   │   │   ├── test.md
  | │   │   ├─── itOnlyShowsThisFile.md
  | │   ├── contact
  | │   ├── signup
```

But the Content Manager won't fetch these entries. It only fetches entries located in src/content/news which is not the expected behaviour.

### Steps to reproduce

My collection looks like this

```yml
collections:
  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
```

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

I expected the Content Manager to fetch all files from the `src/content/news/*/*` and display them.

### Actual result

Content Manager only displays files from `src/content/news`

### Environment

```json
{
  "dependencies": {
    "gatsby": "^2.21.24",
    "gatsby-plugin-netlify": "^2.1.35",
    "gatsby-plugin-netlify-cms": "^4.1.41",
    "netlify-cms-app": "^2.11.29",
    "netlify-cms-locales": "^1.12.0",
  }
}
```

**Comment by blainekasten** [comment]
cc @erezrokah, would you be able to advise here?

**Comment by erezrokah** [comment]
Thanks for the mention @blainekasten.
The correct way to save content in sub folders it to use the [`path`](https://www.netlifycms.org/docs/beta-features/#folder-collections-path) configuration.

This should work:

```yaml
collections:
  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    path: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
```

**Comment by Kaltoft** [comment]
Thanks that worked @erezrokah.

However this lead to another problem. When I create new entries for this collection the media library isn't loaded correctly. I can upload new images and they work as expected, but I can't see existing images in the media library, only a "No assets found" message.
After publishing they show up correctly.

I've tried different solutions with `media_library` and `public_library` but none of them seem to work. Using `{{media_folder}}` doesn't work either.

With this setup the files are stored in the correct folder, but the new issue persists.

```yml
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    path: "{{year}}/{{month}}/{{slug}}"
    media_folder: "../../../../../static/img"
    public_folder: "/img"
```

**Comment by erezrokah** [comment]
You can reference absolute paths when using `media_folder` and `public_folder`:

```yaml
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "news"
    label: "News"
    folder: "src/content/news"
    create: true
    path: "{{year}}/{{month}}/{{slug}}"
    media_folder: "/static/img"
    public_folder: "/img"
```

Otherwise the collection level media folder is evaluated relative to the entry (and for new entries display an empty media folder since the CMS needs to save the entry first before knowing where are the media files located).

See more here https://github.com/netlify/netlify-cms/issues/3671
