### ISSUE TITLE
How to self-host fonts?

### ISSUE THREAD

**Issue by ooloth** [gatsbyjs/gatsby#2583]
Self-hosting fonts included in https://github.com/kyleamathews/typefaces is working great for me. However, I'm having trouble self-hosting other fonts.

Following the advice of @KyleAMathews in [this issue](https://github.com/gatsbyjs/gatsby/issues/397), I created a `./src/fonts/` directory and put the font files there. I then imported the font files in `src/layouts/index.js` like this:

```js
import '../fonts/font-file.woff2'
import '../fonts/font-file.woff'
```

I'm expecting to see the files copied to the `./public/` directory, but that isn't happening.

Am I doing something wrong?

**Comment by nealoke** [comment]
Just use `url()` inside the css where you import the font. This should tell webpack to also include this in the build.

**Comment by ooloth** [comment]
@nealoke Thanks for the reply!

What path should I use inside the `url()`? I've tried the following `@font-face` declarations, but none have worked for me (they result in `net::ERR_ABORTED` errors in the console):

## ./
```css
@font-face {
    font-family: 'Font File';
    src: url('./font-file.woff2') format('woff2'),
        url('./font-file.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }
```

## ./static/
```css
@font-face {
    font-family: 'Font File';
    src: url('./static/font-file.woff2') format('woff2'),
        url('./static/font-file.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }
```

## ./fonts/
```css
@font-face {
    font-family: 'Font File';
    src: url('./fonts/font-file.woff2') format('woff2'),
        url('./fonts/font-file.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }
```

## ./static/fonts/
```css
@font-face {
    font-family: 'Font File';
    src: url('./static/fonts/font-file.woff2') format('woff2'),
        url('./static/fonts/font-file.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }
```

**Comment by ooloth** [comment]
In case it helps, using `url(../fonts/font-file.woff2)` in a CSS file imported from the same folder resolves the `net::ERR_ABORTED` error in the console, but the font files are still not copied to `/public/`.

**Comment by ooloth** [comment]
I deleted my earlier replies that contained a few errors.

I added the following `@font-face` declaration to `src/layouts/font-face.css`:

```css
@font-face {
    font-family: 'Font File';
    src: url('..fonts/font-file.woff2') format('woff2'),
        url('..fonts/font-file.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }
```

This resolved the `net::ERR_ABORTED` error in the console, but the font files are still not being copied to `/public/`. Any idea why?

**Comment by m-allanson** [comment]
That looks very similar to the setup I have, which has been working OK. Are you missing a `/` near the beginning of the url paths? e.g. change this:

```
url('..fonts/font-file.woff') format('woff')
```

to 

```
url('../fonts/font-file.woff') format('woff')
```

Also I believe that files are not copied to the `public/` directory if you're running Gatsby's development mode (`gatsby develop`), that only happens in production mode (`gatsby build`). You can check the Network tab of your browser's developer tools to confirm that the font files are loaded when running in development mode.

**Comment by ooloth** [comment]
@m-allanson Apologies for the typo! I had the `/` in my code, but missed it here.

Thanks for clarifying that files are not copied to `public/` in development mode! I see in the Network tab that the font files are being loaded, so everything is actually working properly.

**Comment by monsieurnebo** [comment]
Does it works with `styled-components` style?

I just tried the following code:
```css
  @font-face {
    font-family: "RFRufo-Bold";
    font-style: normal;
    font-weight: normal;
    src: url("../../etc/fonts/RFRufo-Bold.woff") format("woff"), url("../../etc/fonts/RFRufo-Bold.ttf") format("ttf");
  }
```

Which load my font from `/etc/foo/bar`, outside of the `/public/` directory --> works on my computer because there is the /etc/ directory, but it wont be preset on the production server.

Shouldn't Gatsby / Webpack load this file into my `public` dir?
