### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by sohamsj** [gatsbyjs/gatsby#27746]
```yaml
name: french
code: en
maintainers:
  - tesseralis
  - marcysutton
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
