### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by sohamsj** [gatsbyjs/gatsby#27745]
```YAML
name: English
code: en
maintainers:
  - tesseral
  - Marcy Sutton
```

**Maintainers**

If you would like to be a maintainer, please respond to this issue with:

- your experience level in open source
- your level of experience in the target language and localization
- how much time you can commit to being a maintainer
