### ISSUE TITLE
help making yaml files more powerful

### ISSUE THREAD

**Issue by andykais** [gatsbyjs/gatsby#2817]
Hi all, can I get some help writing markdown within a yaml page? I am attempting a switch from jekyll to gatsby, but one of the nice features of jekyll was the [liquid templating language](https://jekyllrb.com/docs/templates/) which allowed you to pass any string (from a yaml file for instance) through a `markdownify` pipe. This was useful when I had several pieces of information I wanted structured on the page but organized together in a yaml file. Example:

```yaml
- title: My Title
  image: ./assets/image.png
  description: >
    Here is a long winded description that includes a [link](https://code-somewhere.com).
- title: Second Item
  image: ./assets/image2.png
  description >
    more text ...
```

On a similar note, loading an image this way seems to not be possible, I have hacky solutions for that, like importing all the images somewhere else in the file, but is there a way to let webpack know to copy any images in the `pages/` folder even if they 'appear' to not be used?
