### ISSUE TITLE
background-image in less rendered as [object Object]

### ISSUE THREAD

**Issue by MichaelCereda** [gatsbyjs/gatsby#287]
I'm trying to add a background-image in a less file.

```less

.contact{
  .fixed-column-container{
    background: url('../assets/intro.jpg') transparent center center no-repeat;
    background-size: 70%;
  }
}

```

but it gets rendered as 

```css
.contact .fixed-column-container {
    background: url([object Object]) transparent center center no-repeat;
    background-size: 70%;
}
```

any suggestion?
thank you

**Comment by patrykkopycinski** [comment]
hey @MichaelCereda do you have loader for .jpg files? because by default Gatbsy doesn't contain any loader for images:
https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L220

**Comment by MichaelCereda** [comment]
Oh.. no .. no loader :S.
I was suspecting about that... thank you.

do you suggest any particular loader? i just wanted the css to render it as plain css

```css
.contact .fixed-column-container {
    background: url('../assets/intro.jpg') transparent center center no-repeat;
    background-size: 70%;
}
```
