### ISSUE TITLE
sitemap.xml isn't made by gatsby-plugin-sitemap in Amplify.

### ISSUE THREAD

**Issue by uekyo** [gatsbyjs/gatsby#29241]
I made a very simple gatsby site with AWS Amplify tho, site map was not created by 'gatsby-plugin-sitemap'.

**[package.json]**
```
{
  "name": "web_matching",
  "version": "1.0.0",
  "private": true,
  "description": "web_matching",
  "author": "uekyo",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "gatsby": "^2.26.1",
    "gatsby-plugin-sitemap": "^2.11.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}
```

**[gatsby-config.js]**
```
module.exports = {
  siteMetadata: {
    title: "web_matching",
    siteUrl: `https://amp.d1aw1cuurv9iud.amplifyapp.com`,
  },
  plugins: [
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/sitemap.xml`,
      }
    }
  ]
};
```

**[amplify.yml]**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Do you guys have the same experience? By the way, if I enter the sitemap URL, it's moved to a top page automatically. However, it works on localhost. The problem seems to be in Amplify.
