### ISSUE TITLE
gatsby-plugin-offline causes site load to fail immediately (before any network requests) on all subsequent visits

### ISSUE THREAD

**Issue by avinoamsn** [gatsbyjs/gatsby#32110]
## Description

This is for a legacy version of the plugin (v2.10), but I still have no idea what's happening under the hood so I figured I'd report it.

Enabling `gatsby-plugin-offline` causes site load to fail immediately (before any network requests) on every subsequent visit. This started happening a couple of weeks ago, but no code changes had been pushed (although the site is rebuilt multiple times a day, so I'm guessing that the breakage coincided with one of those builds). The breakage occurs seemingly randomly, and only some users were reporting the problem. In my experience, I didn't have an issue with Chrome on OSX, but did with Chrome on Win10. The support staff helping me in the thread below was never able to repro the issue.

[Here is a link to a conversation that I'm having on the Netlify support forums, with additional info (incl. build logs & other attempted fixes).](https://answers.netlify.com/t/gatsby-wordpress-site-only-loads-on-a-fresh-browser-session-immediately-fails-on-any-successive-visit/39522)

Please let me know if I can provide any additional info.

### Steps to reproduce

This only occured on my custom domain on Netlify & I've since rm'd the service worker from the site, so the issue isn't easily reproducible. I've included the entire `.har` file below, which is as much context as visiting the site would've offered.

### Expected result

The site should load.

### Actual result

The site immediately fails to load with a generic `err:FAILED`.

Here is the network log `.har`:

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "request": {
          "method": "GET",
          "url": "https://allianceforpatientaccess.org/",
          "httpVersion": "",
          "headers": [
            {
              "name": "sec-ch-ua",
              "value": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_FAILED"
        },
        "serverIPAddress": "",
        "startedDateTime": "2021-06-24T17:46:11.756Z",
        "time": 48.039999906904995,
        "timings": {
          "blocked": 48.039999906904995,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        }
      },
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "request": {
          "method": "GET",
          "url": "https://allianceforpatientaccess.org/",
          "httpVersion": "",
          "headers": [
            {
              "name": "sec-ch-ua",
              "value": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_FAILED"
        },
        "serverIPAddress": "",
        "startedDateTime": "2021-06-24T17:46:12.878Z",
        "time": 8.953000069595873,
        "timings": {
          "blocked": 8.953000069595873,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        }
      },
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "request": {
          "method": "GET",
          "url": "https://allianceforpatientaccess.org/",
          "httpVersion": "",
          "headers": [
            {
              "name": "sec-ch-ua",
              "value": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_FAILED"
        },
        "serverIPAddress": "",
        "startedDateTime": "2021-06-24T17:46:17.907Z",
        "time": 8.12499993480742,
        "timings": {
          "blocked": 8.12499993480742,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        }
      }
    ]
  }
}
```

### Environment

```yaml
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (3) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 3.8.1 - /home/avi/.pyenv/shims/python
  npmPackages:
    gatsby: ^2.18.22 => 2.32.13
    gatsby-background-image: ^0.8.19 => 0.8.19
    gatsby-cli: ^2.12.10 => 2.19.3
    gatsby-gravityforms-component: ^2.0.1 => 2.0.1
    gatsby-image: ^2.2.38 => 2.2.39
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-google-gtag: ^2.1.1 => 2.1.1
    gatsby-plugin-manifest: ^2.2.37 => 2.2.37
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-postcss: ^2.1.19 => 2.3.13
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.3.13 => 2.3.13
    gatsby-plugin-typescript: ^2.1.26 => 2.12.1
    gatsby-source-filesystem: ^2.1.46 => 2.11.1
    gatsby-source-gravityforms: ^1.0.15 => 1.0.15
    gatsby-source-wordpress: ^3.3.15 => 3.11.0
    gatsby-transformer-sharp: ^2.3.12 => 2.3.13
```
