### ISSUE TITLE
Production build of gatsby (v4) mangles some CSS SVG background images in production builds

### ISSUE THREAD

**Issue by phun-ky** [gatsbyjs/gatsby#34395]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

## Expected Behavior

Some components with CSS SVG background images are not mangled

## Current Behavior

CSS SVG background images are not mangled

Say, this svg:

```html
<svg xmlns='http://www.w3.org/2000/svg' stroke-width='1.5' viewBox='0 0 32 32'>
  <g fill='none' stroke='%23331e11' stroke-linecap='square' stroke-miterlimit='10'>
    <path d='M2 30 30 2'/>
    <path d='M2 22 22 2' data-color='color-2'/>
    <path d='M2 14 14 2'/>
    <path d='m2 6 4-4M10 30l20-20' data-color='color-2'/>
    <path d='m18 30 12-12'/>
    <path d='m26 30 4-4' data-color='color-2'/>
  </g>
</svg>
```

Is mangled to this:

```css
.if.toolbox button.if.toolbox-background-trigger.is-hovered, .if.toolbox button.if.toolbox-background-trigger:hover {
	background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' stroke-width='1.5' viewBox='0 0 32 32'%3E%3Cg fill='none' stroke='%230054f0' stroke-linecap='square' stroke-miterlimit='10'%3E%3Cpath d='M2 30 30 2'/%3E%3Cpath d='M2 22 22 2' data-color='color-2'/%3E%3Cpath d='M2 14 14 2'/%3E%3C/g%3E%3C/svg%3E");
}
```

Formatted pure SVG:

```html
<svg xmlns='http://www.w3.org/2000/svg' stroke-width='1.5' viewBox='0 0 32 32'>
  <g fill='none' stroke='%230054f0' stroke-linecap='square' stroke-miterlimit='10'>
    <path d='M2 30 30 2'/>
    <path d='M2 22 22 2' data-color='color-2'/>
    <path d='M2 14 14 2'/>
  </g>
</svg>
```

This happens for the same icons, for every build, only 2-5 icons out off 30+, and only icons as svg backgrounds, built from `*.styl` files. **ONLY** for production builds, locally and on release.

This happened after upgrading to v4. Could this be `postcss` that is greedy? No SVG background is broken, it seems to just missing a few tags per case.

### Reproduction Link

https://github.com/phun-ky/gatsby-34395

### Steps to Reproduce

1. Clone repo
2. npm i
3. `gatsby build`
4. `gatsby serve`
5. See example on the front page. It's also viewable in production on https://design.if.eu and on sub pages, see screenshots.

![Screenshot from 2022-01-04 13-09-29](https://user-images.githubusercontent.com/1714029/148057060-c9bd32a7-0d25-4c5f-8d36-cfb57991219a.png)
![Screenshot from 2022-01-04 13-06-50](https://user-images.githubusercontent.com/1714029/148057062-e1330cf1-cf9d-4c48-af12-b8e58c5e93ff.png)

### Expected Result

Some CSS SVG background images are NOT mangled

### Actual Result

Some CSS SVG background images are mangled

### Environment

```shell
  System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 8.2.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0
    gatsby-plugin-stylus: ^4.0.0 => 4.4.0
  npmGlobalPackages:
    gatsby: 4.4.0

```
