### ISSUE TITLE
Add date formatting query options to lists of date strings in YAML in addition to scalars

### ISSUE THREAD

**Issue by lourd** [gatsbyjs/gatsby#3556]
## Description

The `gatsby-transformer-yaml` plugin has a great behavior for parsing date strings and exposing them as rich Dates with the ability to format them through GraphQL query parameters! The ability to write simple, human-readable date strings like `2018-01-01` in YAML and have a rich date to query against for things like days of the week, abbreviations, etc., is excellent.

I was disappointed to discover that this feature is limited to scalars. Creating a list of date strings exposes no ability to format all of them through the query.

My workaround is to add another object layer, e.g. a list of objects that have a single property called date, but it would be nice to not have to do that.

### Environment

Gatsby version: 1.9.151
Node.js version: 8.9
Operating System: macOS Siera 10.12.6

#### Data

```yaml
# events.yaml
# assume configured for processing with gatsby-source-filesystem

- name: Greatest show on earth
  dates:
    - 2018-01-01
    - 2018-01-02
    - 2018-01-03
- name: Average show
  dates:
    - 2018-01-04
    - 2018-01-05
    - 2018-01-06
```

#### Query

```graphql
query EventsQuery {
  allEventsYaml {
    edges {
      node {
        name
        dates(formatString: "ddd MMMM Do, YYYY")
      }
    }
  }
}
```

#### Desired result

```json
{
  "data": {
    "allEventsYaml": {
      "edges" : [
        {
          "node": {
            "name": "Greatest show on earth",
            "dates": [
              "Monday January 1st, 2018",
              "Tuesday January 2nd, 2018",
              "Wednesday January 3rd, 2018",
            ],
          },
        },
        {
          "node": {
            "name": "Average show",
            "dates": [
              "Thursday January 4th, 2018",
              "Friday January 5th, 2018",
              "Saturday January 6th, 2018",
            ]
          }
        }
      ]
    }
  }
}
```

#### Current result

```json
{
  "errors": [
    {
      "message": "Unknown argument \"formatString\" on field \"dates\" of type \"EventsYaml\".",
      "locations": [
        {
          "line": 30,
          "column": 23
        }
      ]
    }
  ]
}
