### ISSUE TITLE
[gatsby-source-wordpress] url rewriting for files no longer works when updating the wordpress page while dev server runs

### ISSUE THREAD

**Issue by rburgst** [gatsbyjs/gatsby#35691]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

It looks as if audio files within custom fields are no longer being downloaded and rewritten to local links in the case where you have a dev server running and update the page in wordpress. This used to work with gatsby <= 4.9.x.

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-wordpress-blog

### Steps to Reproduce

1. create a new wordpress instance, e.g. via the following docker file:
 ```yaml
  version: "3.9"
    
services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}
```
2. add the following plugins
  ** wp-gatsby
  ** wpgraphql
  ** advanced custom fields
  ** wpgraphql advanced custom fields
3. create a customfield group e.g. `foofield` which is linked to posts
4. add a field `contentField` of type `wysiwyg`
5. go to the sample post that comes with the standard wordpress installation
6. in the custom field editor add some text as well as an mp3 audio 
7. now start the gatsby dev server and query the custom field with the following query
 ```
  query MyQuery {
  allWpPost {
    nodes {
      content
      foofield {
        contentfield
      }
    }
  }
}
```

### Expected Result

the HTML content in the custom field should contain an `<audio>` tag that contains the rewritten audio mp3.

### Actual Result

```
{
  "data": {
    "allWpPost": {
      "nodes": [
        {
          "content": "\n<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>\n\n\n\n<figure class=\"wp-block-audio\"><audio controls src=\"http://localhost:8000/wp-content/uploads/2022/05/Aufloesung_stimmen1_2_3_4-klavier_SW.mp3\"></audio></figure>\n",
          "foofield": {
            "contentfield": "<p>foo content</p>\n<!--[if lt IE 9]><script>document.createElement('audio');</script><![endif]-->\n<audio class=\"wp-audio-shortcode\" id=\"audio-1-1\" preload=\"none\" style=\"width: 100%;\" controls=\"controls\"><source type=\"audio/mpeg\" src=\"http://localhost:8000/wp-content/uploads/2022/05/Aufloesung_stimmen1_2_3_4-klavier_SW.mp3?_=1\" /><a href=\"http://localhost:8000/wp-content/uploads/2022/05/Aufloesung_stimmen1_2_3_4-klavier_SW.mp3\">http://localhost:8000/wp-content/uploads/2022/05/Aufloesung_stimmen1_2_3_4-klavier_SW.mp3</a></audio>\n"
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

Note that the `src` attribute points to the original wordpress url of the mp3 file.

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/9h/6y70jr3x7cb4cykkjldnppgc0000gn/T/yarn--1652892929785-0.9133048353254971/node
    Yarn: 1.22.18 - /var/folders/9h/6y70jr3x7cb4cykkjldnppgc0000gn/T/yarn--1652892929785-0.9133048353254971/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.1
    Safari: 15.4
  npmPackages:
    gatsby: ^4.0.0 => 4.14.0 
    gatsby-plugin-image: ^2.0.0 => 2.14.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.14.0 
    gatsby-plugin-offline: ^5.0.0 => 5.14.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.14.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.14.0 
    gatsby-source-filesystem: ^4.0.0 => 4.14.0 
    gatsby-source-wordpress: ^6.0.0 => 6.14.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.14.0
```

### Config Flags

N/A, none have been configured in the sample wordpress repo.
