### ISSUE TITLE
CSS Modules build output hash not escaped

### ISSUE THREAD

**Issue by Noam-Bendelac** [gatsbyjs/gatsby#36673]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When a CSS Module hash of a class name contains certain characters like `+`, it doesn't always get escaped correctly. The code
```css
@value classA from "./A.module.css";
@value print from "./A.module.css";

.classA .classB {
  color: red;
}

.print .classB {
  color: red;
}
```
Compiles into:
```css
.A-module--classA--y8IDI {
}

.A-module--print--24b\+W {
}

.A-module--classA--y8IDI .B-module--classB--oWRdE {
  color: red;
}

.A-module--print--24b+W .B-module--classB--oWRdE {
  color: red;
}
```
`.A-module--print--24b\+W` is correctly escaped. `.A-module--print--24b+W` gets parsed as `.A-module--print--24b + W` because of the lack of escape character. Other class names whose hashes don't contain `+` work fine. If this is an issue with an external library Gatsby uses, where should I file that bug?

### Reproduction Link

https://codesandbox.io/s/brave-grass-7fx9gn

### Steps to Reproduce

1. Write css module code as in the CodeSandbox, where an imported class is used as an ancestor in a css selector.
2. Different class names will have different hashes. If the hash contains a `+` symbol, the generated css will be broken.

### Expected Result

The generated code should escape the class name every time:
```css
.A-module--print--24b\+W {
}

.A-module--print--24b\+W .B-module--classB--oWRdE {
  color: red;
}
```

### Actual Result

The generated code does not escape the class name if used as an ancestor:
```css
.A-module--print--24b\+W {
}

.A-module--print--24b+W .B-module--classB--oWRdE {
  color: red;
}
```

### Environment

```shell
System:
    OS: Linux 5.13 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^4.23.1 => 4.23.1
```
