### ISSUE TITLE
GitLab Pages Supports Gatsby

### ISSUE THREAD

**Issue by michaeljdeeb** [gatsbyjs/gatsby#497]
[Git**Lab** Pages](http://pages.gitlab.io) is very similar to Git**Hub** Pages, but it supports any static website generator.

Once you're setup following their instructions, you just need to add a file at the root of the repository named `.gitlab-ci.yml` that looks like this:

``` yaml
image: node:4.6.0

pages:
  script:
  - npm install -sg gatsby
  - npm install -q
  - gatsby build
  artifacts:
    paths:
    - public
  only:
  - master
```

Which tells GitLab how to build your project.

This is a great way to get started using Gatsby for free, they support [TLS](https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/), and in my experience it was much easier to work with compared to a GitHub+Travis solution.

**Comment by michaeljdeeb** [comment]
The above `.gitlab-ci.yml` example was rather quickly because I was excited and wanted to get results fast. A local install of gatsby might save some time?

`-s` and `-q` were used because GitLab has a log limit that gets hit otherwise and I ran into a few errors getting to a solution.

**Comment by KyleAMathews** [comment]
This is great @michaeljdeeb! This will be perfect to add to a "hosts" section of the new website.

**Comment by KyleAMathews** [comment]
Yeah, using `./node_modules/.bin/gatsby` to do the build saves having to double-install Gatsby.

**Comment by vicodinchik** [comment]
@KyleAMathews does it mean that we should push node modules bin of gatsby? Didn't got that part

**Comment by KyleAMathews** [comment]
I was just saying you don't need to globally install Gatsby on a build server as you can use the local install.

**Comment by jbolda** [comment]
@michaeljdeeb with the launch of 1.0, it might be nice to create a quick example site of this to add to the repo (master branch: ./examples).

**Comment by michaeljdeeb** [comment]
Currently testing a `gatsby new` site with a slightly better `.gitlab-ci.yml`, but the job has been pending for an unacceptable amount of time compared to GitHub Pages or Netlify.

**Comment by michaeljdeeb** [comment]
So the slowdown was caused by an [outage](https://twitter.com/gitlabstatus/status/884867369088299009) and I managed to get `gatsby-starter-defualt` building.

I can continue in this direction and add in some sample text on the site about how to deploy and why you might want to and pop it in ./examples/, but the only special thing needed is `.gitlab-ci.yml`.

Is a deployment section of the docs still on the roadmap for gatsbyjs.org? I think putting the steps there alongside Netlify, GitHub Pages, and others would make more sense.

Also here's the updated `.gitlab-ci.yml` for anybody else coming here:
```yml
image: node:8.1.3

pages:
  script:
  # npm install fails with node v8.x.x so we'll use yarn instead
  # - npm install
  - npm install -g yarn
  - yarn install
  - ./node_modules/.bin/gatsby build
  artifacts:
    paths:
    - public
  only:
  - master
```
