### ISSUE TITLE
How to do "join" with graphql ?

### ISSUE THREAD

**Issue by deemaagog** [gatsbyjs/gatsby#5280]
Hi all . I use gatsby and netlify cms.
My schema:
```
collections:
  - name: "tags"
    label: "Tags"
    folder: "src/data/tags"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Id", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - name: "posts"
    label: "Posts"
    folder: "src/data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Id", name: "title", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - label: "Tag"
            name: "tag"
            widget: "relation"
            collection: "tags"
            searchFields: [ "description"]
            valueField: "title"
            displayFields: ["description"]
```

My query:
```
query PostByID($id: String!) {
    markdownRemark(id: { eq: $id }) {
      id
      html
      frontmatter {
        id: title
        description
        tags {
            tag
            // get tag description????
        }
      }
    }
  }
```

Is there a way to get tag description ?
