### ISSUE TITLE
gatsby-transformer-remark cannot handle an array of objects

### ISSUE THREAD

**Issue by deltaskelta** [gatsbyjs/gatsby#5372]
## Description

The frontmatter cannot handle an array of objects, and seems to call `toString()` on the object somewhere

### Steps to reproduce

add a frontmatter like this

```
authors:
  - name: foo
    avatar: ../../path
    page: /path/to/page
  - name: bar
    avatar: ../../path2
    page: /path/to/page
```

and print it to the console to see this 

```

authors:Array(2)
  0:"[object Object]"
  1:"[object Object]"
```

### Expected result

I would expect to see my array of objects in the frontmatter

### Actual result

I get the string representation of the object

### Environment
* Gatsby version (`npm list gatsby`): 1.9.250
* gatsby-cli version (`gatsby --version`): 1.9.260
* Node.js version: 10.1.0
* Operating System: OSSierra 10.13.4

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A
