### ISSUE TITLE
Introspection Query (if not rootType) is not available when creating pages

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#5674]
I would like to read my fields available from a specific Type.

```graphql
__type(name: "datasheet_2") {
    fields {
      name
    }
  }
```
See image below, it will generate a null result the first time building, but the second time its there!
Suggesting the schema is generated afterwards..

![grafik](https://user-images.githubusercontent.com/5635709/40872124-2f05a668-6649-11e8-9b97-1fcd1c5ccff4.png)

Is it possible to hook after the update schema step and have the result passed to context of pages?

**Comment by pungggi** [comment]
This would solve my case that seems not possible with the graphql specification see https://github.com/gatsbyjs/gatsby/issues/5635

**Comment by pungggi** [comment]
Interesting by quering the root type i get a result:
```
  __type(name: "SpecificationsYaml") {
    fields {
      name
    }
  }
```

my data structure is as follows:

```yaml
title: New Machine T800
entryDate: 21.05.18
isPromoted: true
mediaimages:
  - image: /media/imgkallfass_aus2.jpg
  - image: /media/imgmccain1500_2_small.jpg
datasheet:
  data_available: July 2018
  data_impressions: 22 Mio.
  data_location: Switzerland
  data_units: '6'
  data_year: '2013'
description: |-
  fsfsfsdf saf.
  sdfas
```
Basically I want to query the fields unter Datasheet..
