### ISSUE TITLE
gatsby-transformer-yaml errors on keys that are integers

### ISSUE THREAD

**Issue by master12** [gatsbyjs/gatsby#6470]
## Description

Yaml with integers as keys fails with this error:

error UNHANDLED REJECTION

  Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "2006" does not.

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach

  - Array.forEach

This is the yaml used:

```
US:
  products:
    Coal:
      units: short tons
      volume:
        '2006': 1162749659
```

This is valid yaml.

### Steps to reproduce

Use the gatsby-transformer-yaml plugin 

### Expected result

Should be valid yaml

### Actual result

Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "2006" does not.

### Environment

gatsby 1.1.52
Windows 10

**Comment by pieh** [comment]
This is requirement of `graphql` - field names can't start with number - as a workaround You can prefix `2006` with letter or underscore or remodel your yaml to use array instead of map/dictionary:
```yaml
US:
  products:
    Coal:
      units: short tons
      volume:
        - key: 2006
          value: 1162749659
```
I would say second is better, because with first you will need to directly query for fields like `_2006`, but I suspect that's dynamic, right?
