### ISSUE TITLE
Web Sites keeps loading infinitely on Safari?

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#7383]
If you visit [my website](http://akshaykadam.me) & go to **Apps** on Safari, it keeps on redirecting again & again.

And in console there is some weird error `TypeError: undefined is not an object (evaluating 'this.state.pageResources.json.pageContext')`.

I think something is wrong with the static **pages.json** or **path.json** it generates after building the site.

In Chrome or Firefox this works all fine. No issues at all. Has anyone ever faced this issue?

**Comment by deadcoder0904** [comment]
Another issue is when I append a slash at the end of the url like https://akshaykadam.me/apps/lessons-of-hn-bot/ then it loads without CSS.

And if I visit the website from another URL it also keeps infinitely loading. Like from https://wip.chat/products/1415 or https://wip.chat/products/1678

Click on the green button below profile. It should keep loading infinitely. Weird issue I don't know what's causing.

**Comment by davidbailey00** [comment]
Is this v2? If so, it might be fixed with #7355

**Comment by deadcoder0904** [comment]
Hey when I slept I found the solution. I remembered my `gatsby` version in `package.json` is `@next` & Gatsby switched from `react-router` to `@reach/router` so that might be the issue for redirects or infinite load.

I just woke up so I'll migrate now & see if it works & close this issue when it does.

**Comment by deadcoder0904** [comment]
If it doesn't work after migrating to `@reach/router` then I'll try your solution @davidbailey00

**Comment by deadcoder0904** [comment]
Ohh no so I tried migrating. But it looks like I didn't have anything to migrate at all. I'm only using Link. Although there was one issue that I was importing it from `gatsby-link` but now have imported from `gatsby` but it still doesn't work.

Even when I hit refresh on Safari it doesn't load the CSS. Everything works great on Firefox & Chrome but the issue persists on Safari. 

I guess @davidbailey00 its the issue you are talking about as I have `gatsby-plugin-offline` installed plus a bunch of other stuff.

```yml
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.110 
    gatsby-image: next => 2.0.0-beta.8 
    gatsby-plugin-emotion: next => 2.0.0-beta.3 
    gatsby-plugin-feed: next => 2.0.0-beta.4 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.5 
    gatsby-plugin-manifest: next => 2.0.2-beta.6 
    gatsby-plugin-netlify: next => 2.0.0-beta.6 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: next => 2.0.0-beta.4 
    gatsby-plugin-offline: next => 2.0.0-beta.9 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: next => 2.0.0-beta.9 
    gatsby-plugin-sitemap: next => 2.0.0-beta.4 
    gatsby-plugin-twitter: next => 2.0.0-beta.3 
    gatsby-remark-images: next => 2.0.1-beta.11 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-remark: next => 2.1.1-beta.6 
    gatsby-transformer-sharp: next => 2.1.1-beta.7 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```
