### ISSUE TITLE
Production build alphabetizes css rules (breaking your CSS)

### ISSUE THREAD

**Issue by ryanflorence** [gatsbyjs/gatsby#7638]
I have declared in my code:

```css
hr {
  border-width: 0;
  border-top: 1px solid #e1e1e1;
}
```

And that's how it looks in development.

But in production all of my CSS gets alphabetized some how (😬) resulting in this:

```css
hr {
  border-top: 1px solid #e1e1e1;
  border-width: 0;
}
```

And as you know, this leads to wildly different results, the `<hr>` doesn't get a border applied to it. I'm now concerned about what other bugs there are that I haven't found yet because of this.

Any idea which webpack loader is doing this and is there a way to disable it?

I even tried to outsmart it:

```css
hr {
  border-width: 0;
}

hr {
  border-top: 1px solid #e1e1e1;
}
```

But it merged those two rules and alphabetized the rules again 🤣
