### ISSUE TITLE
[v2] Gatsby attempts to reload a page infinitely if the canonical path doesn't match window.location.pathname

### ISSUE THREAD

**Issue by davidbailey00** [gatsbyjs/gatsby#7760]
This is mainly a problem when the hosting rewrites uppercase URLs as lowercase, and would also occur e.g. if an external link points to a page on a Gatsby site with different casing. To test locally, after running `gatsby build` and before `gatsby serve`, copy a page folder to another location (e.g. `cp -r public/about public/about-test`).

Analysis so far: replacing `window.location.pathname` with `window.page.path` in `production-app.js` (around lines 85) prevents the `A page wasn't found for...` warning displaying in the console, and `loader.getPage(window.page.path)` returns `true`:

![image](https://user-images.githubusercontent.com/4248177/44882695-5712c380-acac-11e8-8d53-e6967b76a20d.png)

(In the future I'll also perform checks to make sure it still uses `window.location.pathname` if the canonical path points to the offline app shell, otherwise it would just render a blank page without `no-cache=1`.)

However, the RouteHandler element's `props.location` still use the actual window's location, and these props are used to determine which page to actually load. I believe they get passed to `PageRenderer` which then checks if the `pageResources` exist, and this check fails due to the actual pathname for which Gatsby doesn't have resources. Thus we have the infinite reload, where `&no-cache=1` keeps getting added to the URL: (while testing I returned null before this happens to make things easier, but normally that line wouldn't exist so it would keep reloading)

![image](https://user-images.githubusercontent.com/4248177/44882922-4878dc00-acad-11e8-97ae-afefadbb32ea.png)

So what we need to do is set change the RouteHandler's `props.location.pathname` to match the canonical path, to allow Gatsby to find the resources. This is what I'm currently stuck on, I'll just copy my last commend from #7355 over here

**Comment by davidbailey00** [comment]
cc @KyleAMathews @jlengstorf @m-allanson I'm really struggling to understand where `RouteHandler` gets its props from, can someone help me out? I'm testing by making a copy of the `about` folder to `about-test`, to see if I can get it to load correctly using the canonical path (`window.page.path`) rather than the URL's actual path.

If I log the props...

![image](https://user-images.githubusercontent.com/4248177/44881952-4a40a080-aca9-11e8-8f58-35c492120e4c.png)

...it's clear that the `location` prop is set from `window.location`:

![image](https://user-images.githubusercontent.com/4248177/44881982-63495180-aca9-11e8-8a1e-971e50b3bd8a.png)

But after running a trace I still have no idea how it gets these props. The element itself is created at line 126 (in my local code with added `console.log`s) when the `renderer` function is called:

![image](https://user-images.githubusercontent.com/4248177/44882075-bf13da80-aca9-11e8-8f15-99b32d6dc1d8.png)

...since it renders `NewRoute`, which wraps the `RouteHandler` element. It's clear that the only prop passed is the `path` prop:

![image](https://user-images.githubusercontent.com/4248177/44882113-e074c680-aca9-11e8-9e60-1d16657bd380.png)

All function calls between line 126 and the `RouteHandler` constructor are React calls, which can be seen via the console trace:

![image](https://user-images.githubusercontent.com/4248177/44882211-46f9e480-acaa-11e8-9f37-24f524427682.png)

All the other calls are higher-level and have no mention of `location` or anything like that. My guess is that Reach Router must be adding the props, but I don't understand it well enough to know how this works... Could someone help me out please?

**Comment by KyleAMathews** [comment]
What is `window.page`? I have no idea why that exists.

**Comment by davidbailey00** [comment]
@KyleAMathews It's added to the HTML at build-time by `cache-dir/static-entry.js` and refers to the canonical path (among some other things):

![image](https://user-images.githubusercontent.com/4248177/44883574-7b23d400-acaf-11e8-9903-269e75fc255b.png)

![image](https://user-images.githubusercontent.com/4248177/44883579-81b24b80-acaf-11e8-9745-1d432d93323e.png)

I'm not sure of its original purpose but it seems perfect for this sort of thing.

**Comment by davidbailey00** [comment]
Alternative way to fix this that I've just thought of, which might be easier - in `production-app.js` which, in my local version, currently has this code:

![image](https://user-images.githubusercontent.com/4248177/44883656-cdfd8b80-acaf-11e8-9e32-5b13b912ffc7.png)

We could use the router to rewrite the URL to the canonical value (rather than trying to load it from the server, as this would still cause infinite loops with e.g. Netlify since it would get rewritten again) - thus changing the `window.location.pathname` which many other parts of the code refer to, e.g. to fetch the page resources.

**Comment by KyleAMathews** [comment]
Oh right @pieh 😅

**Comment by KyleAMathews** [comment]
Why don't we just show a 404 here?

**Comment by davidbailey00** [comment]
> Why don't we just show a 404 here?

It would be much better from a UX perspective (and *maybe* SEO too) to render the page properly if we can, given that we have the canonical path, because it might just be a case of someone clicking a link which uses the wrong case (the server would need to support this behaviour too, otherwise we would get a 404 anyway) or the problem with Netlify where it rewrites URLs as lowercase.

**Comment by KyleAMathews** [comment]
Ah ok, I get it now. The server _has_ matched the page so we should support that. If a link on a site is wrong though, that's on the developer to fix.

**Comment by davidbailey00** [comment]
Yep, this is primarily for when the server returns a page but with a different URL - although if a dev linked to a wrongly-cased URL which the server can serve, then this behaviour which I'm working on would apply there too (albeit it would have to load the page with `?no-cache=1` thus breaking the smooth transitions).

**Comment by KyleAMathews** [comment]
👍

**Comment by davidbailey00** [comment]
I've got the fix done for this issue now, but it's breaking back button navigation at the moment so I'm just trying o get that to work properly.

**Comment by jlengstorf** [comment]
@davidbailey00 does Reach have support for replacing the current history entry? Could be a good workaround to avoid redirect issues in history.

**Comment by davidbailey00** [comment]
@jlengstorf It does, but there were problems whether I used `replace: true` or `replace: false`. But I think these are caused by my `navigate-directly-or-404.js` so it should be fairly easy to fix (I already got it working by changing one of the lines in that file, but just need to check if it broke other behaviour).

**Comment by davidbailey00** [comment]
I think I'll combine this fix with one for the bug I noticed the other day, since they might be more related than I first thought ([source](https://github.com/gatsbyjs/gatsby/pull/7355#issuecomment-417109262)):

> On the note of this, I just noticed that URL search queries aren't always kept when redirecting to `?no-cache=1` - given the Netlify problem, https://www.simeonsmith.me/coding-with-kids/2018/08/10/crab-trap-alpha?no-cache=1 should keep adding `&no-cache=1` when reloading. A better demonstration of the problem:
> 
> 1. Go to https://wizardly-babbage-0faa32.netlify.com/ and wait for the SW to install
> 
> 2. Then go to https://wizardly-babbage-0faa32.netlify.com/admin/?somequery=1 (should be handled by the service worker)
> 
> 3. Expected behaviour: redirects to https://wizardly-babbage-0faa32.netlify.com/admin/?somequery=1&no-cache=1
> 
>    Actual behaviour: redirects to https://wizardly-babbage-0faa32.netlify.com/admin/?no-cache=1

**Comment by davidbailey00** [comment]
I'm just running my changes through the manual test suite

**Comment by davidbailey00** [comment]
Nearly finished manual testing (after fixing a few problems it picked up) - all is looking good, so I should be able to create the PR soon!

**Comment by davidbailey00** [comment]
All tests are passing! PR incoming

/cc @dfmarulanda

<details>
<summary>Tests (now  68)</summary>

```
configurations:

- 1) online without gatsby-plugin-offline
- 2) online with gatsby-plugin-offline
- 3) offline with gatsby-plugin-offline
- 4) online in develop

- x.1) with a custom 404 page
- x.2) without a custom 404 page


tests:

- 1) 404s are handled correctly from internal links - custom 404 or server 404
  if custom is unavailable, or offline error, but no blank pages

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 2) 404s are handled correctly when entering a URL directly - as above, and
  the URL fetched contains the original query parameters (not just no-cache=1)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 3A) back button works properly after internal link 404 (navigates to the
  expected page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 3B) back button works properly after external link 404 (navigates to the
  expected page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 4) pages which fail to load display a native offline error (no blank pages)

  requires: [3.1, 3.2]
  passed:   [3.1, 3.2]

- 5) the service worker remains installed after a 404/offline error

  requires: [3.1, 3.2]
  passed:   [3.1, 3.2]

- 6) Netlify CMS /admin/ loads or displays an offline error (no 404/blank page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 7) going to a page by entering the URL directly works

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 8) clicking the "mismatching canonical URL" link works with JS, and goes
  backwards and forwards correctly (or shows offline)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]

- 9) directly entering the mismatching canonical URL works with JS, and goes
  backwards and forwards correctly (or shows offline)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]

- 10) going to a page with a mismatching canonical URL always shows a 404 in
  development

  requires: [4.1, 4.2]
  passed:   [4.1, 4.2]
```
</details>
