### ISSUE TITLE
How to make siderbar as in version 2

### ISSUE THREAD

**Issue by aman-developer** [gatsbyjs/gatsby#7772]
Hii
I am working on static site using gatsby.
I want to make dropdown sidebar as in version 2 
Url below.
https://next.gatsbyjs.org/docs/

But do not know how to start with it. 
Can you provide me example.
Please help

**Comment by fk** [comment]
Hi @aman-developer! 👋

The [`www`](https://github.com/gatsbyjs/gatsby/tree/master/www) folder in the [`master`](https://github.com/gatsbyjs/gatsby) branch contains the source for https://next.gatsbyjs.org/.
Looking at

* [`www/src/components/sidebar`](https://github.com/gatsbyjs/gatsby/tree/master/www/src/components/sidebar)
* [`www/src/utils/sidebar`](https://github.com/gatsbyjs/gatsby/tree/master/www/src/utils/sidebar)
* [`www/src/data/sidebars`](https://github.com/gatsbyjs/gatsby/tree/master/www/src/data/sidebars)
* [www/src/components/page-with-sidebar.js](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/page-with-sidebar.js)
* https://github.com/gatsbyjs/gatsby/blob/b7508d6800255d34ff868306d6087031359e97da/www/src/pages/docs/index.js#L15
* https://github.com/gatsbyjs/gatsby/blob/b7508d6800255d34ff868306d6087031359e97da/www/src/components/layout.js#L204-L210

should hopefully get you started!

**Comment by aman-developer** [comment]
I had posted one reply here but its not showing. I am getting these errors. 
![screenshot from 2018-09-02 19-21-04](https://user-images.githubusercontent.com/29298440/44967868-d8df4700-af61-11e8-9565-b47289550f66.png)
![screenshot from 2018-09-02 19-21-21](https://user-images.githubusercontent.com/29298440/44967870-dd0b6480-af61-11e8-9b72-96edf7f1c787.png)
![screenshot from 2018-09-02 19-21-26](https://user-images.githubusercontent.com/29298440/44967871-e0065500-af61-11e8-96fa-b2b7cdfcb445.png)

**Comment by aman-developer** [comment]
is there any solution ?

**Comment by fk** [comment]
Hey @aman-developer, sorry to see you having trouble.
Could you try trimming down `docs/sites.yml` to only contain

```
- title: ReactJS
  main_url: "https://reactjs.org/"
  url: "https://reactjs.org/"
  source_url: "https://github.com/reactjs/reactjs.org"
  featured: true
  categories:
    - Web Dev
    - Featured
- title: NEON
  main_url: "http://neonrated.com/"
  url: "http://neonrated.com/"
  featured: true
  categories:
    - Gallery
    - Cinema
    - Featured
- title: The State of European Tech
  main_url: "https://2017.stateofeuropeantech.com/"
  url: "https://2017.stateofeuropeantech.com/"
  featured: true
  description: "foo"
  categories:
    - Featured
    - Technology
  plugins: "gatsby-plugin-react-helmet, gatsby-plugin-react-next"
  built_by: Studio Lovelock
  built_by_url: "http://www.studiolovelock.com/"
```

and let us know if that gets you past the `gatsby-transformer-screenshot` errors?
