### ISSUE TITLE
[www] Did we delete your blog from the site showcase?

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#8934]
We’re getting ready to introduce new YAML validation for the site showcase, so I’m cleaning up entries that don't pass validation right now. It looks like we have quite a few showcase entries that are missing pretty much all of their data.

@gatsbyjs/maintainers (sorry for the mass ping) can you please make sure your site isn't included in the list below? If it is, can you please re-add it to the showcase after https://github.com/gatsbyjs/gatsby/pull/8933 merges.

We'll close this issue on Nov 1.

```yaml
- title: HBTU MUN 2018 (source)
  featured: false
- title: Jamie Henson's Blog (source)
  featured: false
- title: Ruben's Blog (source)
  featured: false
- title: Thao Am Private Enterprise
  featured: false
- title: Bakadono
  featured: false
- title: Travellers.cafe
  featured: false
- title: Oliver Benns' Portfolio (source)
  featured: false
- title: angeloocana.com (source)
  featured: false
- title: Overlap.show (source)
  featured: false
- title: smartive Company Website
  featured: false
- title: Haboba Find Jobs at Phu Quoc Island
  featured: false
- title: Song Wang’s website (source)
  featured: false
- title: Magicly's blog (source)
  featured: false
- title: Phu Quoc Works
  featured: false
- title: Kabir Goel's website (source)
  featured: false
- title: David James' Portfolio (source)
  featured: false
- title: Tic Tac Toe AI (source)
  featured: false
- title: Random Screencast
  featured: false
- title: Phu Quoc Tea & Coffee Store
  featured: false
- title: Steven Natera's blog
  featured: false
- title: Georgi Yanev (source)
  featured: false
- title: Hallingdata
  featured: false
- title: "@swyx (source)"
  featured: false
- title: 伊撒尔の窝
  featured: false
```
