### ISSUE TITLE
Cannot run gatsby build in Bitbucket Pipeline

### ISSUE THREAD

**Issue by tsmith123** [gatsbyjs/gatsby#9096]
## Description

I cannot run 'gatsby build' on a Bitbucket Pipeline.

### Steps to reproduce

image: node:8.12.0

```
pipelines:
  branches:
    dev:
      - step:
          script:
           - apt-get update
           - apt-get -y install python-dev
           - apt-get -y install python-pip
           - pip install awscli
           - npm install
           - npm install --global gatsby-cli
           - gatsby build
           - aws s3 sync public/ s3://my-bucket --acl --delete public-read
```

### Expected result

Locally, running `gatsby build` everything works fine. The pipeline should build in the same way as local

### Actual result

This error is in the `gatsby build` step:

![image](https://user-images.githubusercontent.com/7639854/46914688-a41ad280-cf98-11e8-9ffc-aabcda53252a.png)

### Environment

Shown above
